[자동차 경주 리팩터링] 예니 미션 제출합니다.
woowacourse/kotlin-racingcar pull request #111
Opened 2024-02-16 10:08 UTC by JoYehyun99

잘 부탁드립니다 ☺️

2024-02-16 13:39 UTC, ghojeong requested changes
안녕하세요 예니님!
step1 부터 이미 model, view, controller 를 분리해주셔서,
매우 빠르게 step2 를 구현하시고 PR 을 주셨군요! 👍 

step1 과 다르게 step2 는 좀더 엄격하게 리뷰를 하고자 합니다.
model 패키지의 테스트 커버리지가 100%가 될 수 있도록 테스트 작성 부탁드립니다! 🔥

2024-02-16 13:39 UTC, ghojeong commented on src/test/kotlin/racingcar/model/RacingCarGameTest.kt
> +    fun `무작위 값이 4 미만일 경우 - 해당 자동차는 움직이지 않는다`() {
테스트 명을 상세하게 적어주신 점 좋습니다. 👍 
덕분에 협업 중 테스트가 실패하더라도,
동료가 테스트에 맞춰서 로직을 어떻게 수정해야할지 충분히 힌트가 주어진 듯 합니다.

2024-02-16 13:39 UTC, ghojeong commented on src/test/kotlin/racingcar/model/RacingCarGameTest.kt
> +        assertThat(actual).isEqualTo(expected)
이미 리스트 자체를 비교하는 부분이 있는데 리스트의 size 를 비교하는 것은 테스트의 군더더기 처럼 보입니다.

2024-02-16 13:39 UTC, ghojeong commented on src/main/kotlin/racingcar/view/InputView.kt
> +        return carName.trim().split(",").map { it.trim() }
지난번 피드백 대로 trim 훌륭하게 활용해주셨습니다. 👍 
안드로이드 개발하다가 일어나는 예기치 못한 크래시 중에서는,
이렇게 문자열 파싱 실패나, null 에 대한 잘못된 예외처리가 원인이 많았다는 개인 경험 한번 더 이야기 해봅니다.

2024-02-16 13:39 UTC, ghojeong commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +object InputExceptions {
클래스 명에 관한 사소한 소감을 말씀드려 봅니다.
InputExceptions 객체명을 처음 보았을 때, 저는 이것이 커스텀 예외에 관련된 클래스 인 줄 알았습니다.
하지만 실제 내부를 보니 유틸이었습니다.
유틸 함수와 관련된 object 라는 것을 알 수 있도록 이름을 바꿔주시면 감사하겠습니다.

2024-02-16 13:39 UTC, ghojeong commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +        ) { MESSAGE_ERROR_CAR_NAME_INPUT }
개인적인 개발 경험과 관련된 피드백을 드려봅니다.
이름의 글자수 제한과 시도 횟수는 상당히 빈번하게 바뀔 수 있는 요구사항입니다.
가령 모바일 게임을 구현한다고 했을 때, 기획팀에서 시도 횟수를 1 이상 3 이하로 제한하고,
시도 횟수를 늘려주는 캐시 아이템을 출시하자고 할 수도 있습니다.

자동차 이름의 글자수 제한과, 시도 횟수와 관련된 요구사항이 변경 되었을 때,
에러 메시지, 테스트 코드, 그리고 실제 로직 코드를 어떻게 유지보수를 하실 계획이신가요?

참고로 미션 요구사항을 넘어서는 피드백이므로, 굳이 구현해서 반영을 하지 않아도 괜찮습니다.
그럴 경우는 어떻게 리팩토링하거나 구조를 바꾸어야 할 것 같다고 답변 주시는 것으로 충분합니다.

2024-02-16 13:39 UTC, ghojeong commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
>      }
<img width="565" alt="스크린샷 2024-02-16 오후 10 26 58" src="https://github.com/woowacourse/kotlin-racingcar/assets/38595650/454f1020-7cfd-4974-b1f2-e0934c6800c1">

본인이 테스트를 충분히 작성했는지 확인하는 방법으로 [테스트 커버리지](https://developer.android.com/studio/test/test-in-android-studio#view_test_coverage) 라는 개념이 있습니다.

다른 패키지는 몰라도 model 패키지에서 만큼은 Method 의 테스트 커버리지가 100% 가 될 수 있도록 해주세요.
Line 까지는 지나친 욕심이라 생각되지만, 적어도 model 에서 public 하게 공개된 모든 메서드는 테스트 코드가 작성되어야 합니다.

지금과 같은 상황에서는 Car.toString() 과 RacingCarGame.race()  메서드가 public 하게 공개되어 있음에도,
테스트 코드가 작성되어 있지 않군요.
race() 메서드에 대한 테스트 코드를 짜기가 특히 까다로울거라 생각하는데,
자동차 경주 미션에서 학습해내야 하는 매우 중요한 부분 중 하나입니다.
어렵다면 언제든 질문 주시기 바랍니다.

2024-02-16 15:20 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +object InputExceptions {
입력값과 관련된 예외 처리 객체라고 생각해서 `InputException` 으로 설정했었는데
그렇다면 util 패키지안에 있는 클래스는 보통 `땡땡Utils` 이런 형식으로 짓는게 맞나요?

2024-02-17 02:36 UTC, ghojeong commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +object InputExceptions {
저는 유틸 클래스같은 경우에는 명시적으로 Utils 라고 이름 붙이는 것을 좋아하는 편이기는 합니다.
해당 이름으로 이 클래스에 대한 객체를 생성하면 안된다는 것을 직관적으로 알 수 있으니깐요.

하지만 이것은 저와 함께 협업할 때의 스타일이라 생각해주시고,
다른 리뷰어, 다른 팀에 가면 언제든지 바뀔 수 있다고 생각해주세요.
예니님이 리더 역할을 맡게 되시면, 예니 님이 이러한 규칙을 만드시면 됩니다.
단, 규칙에 일관성은 있어야 합니다.

2024-02-17 12:56 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +        ) { MESSAGE_ERROR_CAR_NAME_INPUT }
생각해보니 입력 형식은 inputView 클래스에서 관리하되, 
실질적인 값의 범위는 `Car`와 `RacingCarGame` 클래스 생성시에 유효성 검사를 진행하는 것이 방법일 것 같습니다.
```kotlin
data class Car(val name: String, var distance: Int = DEFAULT_DISTANCE) {
    init {
        require(name.length < 6) { "자동차 이름은 5자를 초과할 수 없습니다." }
    }
}
```
이렇게 하면 `Car` 객체와 관련된 제한 사항들이 변경되었을 때 `Car`  파일 내에서 해결할 수 있지 않을까... 라는 생각을 해봤습니다.

2024-02-17 13:05 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +        ) { MESSAGE_ERROR_CAR_NAME_INPUT }
사실 원래는 다음과 같이 `RacingCarGame` 클래스 멤버 변수에 시도횟수가 들어가는 것이 더 맞다고 생각했었고, 
위의 `Car` 처럼 클래스를 생성할 때 시도 횟수에 대한 검사를 진행하게 하려면 이러한 구조가 좋을 것 같은데,

```kotlin
class RacingCarGame(private val cars: List<Car>, private val count: Int) {}
```

한 라운드마다 결과값을 출력해야 하는 요구사항 때문에 로직이 꼬여 결국 `count` 값을 controller로 빼내게 되었습니다 🥲

혹시 이러한 부분에서 `시도 횟수`를 게임 컨트롤러가 관리하는 게 좋은지, `RacingCarGame`에서 관리하는게 나은건지 궁금합니다!

2024-02-17 13:06 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +object InputExceptions {
넵 알겠습니다!

2024-02-17 13:11 UTC, ghojeong commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +        ) { MESSAGE_ERROR_CAR_NAME_INPUT }
> 시도 횟수를 게임 컨트롤러가 관리하는 게 좋은지, RacingCarGame에서 관리하는게 나은건지 궁금합니다!

"횟수를 관리" 한다는 말을 코드로 풀어보면, 결국 조건문이 된다고 생각합니다.
그리고 조건문은 튜링 머신에서 데이터가 아닌 머신 자체의 움직임인 로직을 뜻합니다.

로직은 가능한 컨트롤러가 아니라, 모델에서 담당하고 이에 대한 테스트 코드를 함께 작성하는 것을
저는 선호합니다.

다시한번 강조하지만, 시도 횟수에 대한 질문은 이럴 수도 있다~ 의 질문이지,
미션의 요구사항을 벗어나는 내용이므로 가볍게 재미로 생각하고 넘어가주세요. 😄 

다만 현업에서 개발할 때는, 아... 이거 나중에 기획팀이 캐시 아이템으로 넣자고 할 것 같은데... 하고 조심해서 나쁠 것은 없습니다.
미리 해두면 미래의 야근을 방지할 수 있으니까요!

2024-02-17 14:30 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
>      }
음 역시나 어렵네요 😭
일단 생각해본 방법은 

1. `RacingCarGame.race(numberGenerator())`  : 랜덤 숫자를 생성하는 object를 클래스로 수정 후 해당 클래스의 인스턴스를 넘겨줘서 `race` 안에서 메서드를 호출하여 랜덤 숫자 생성

2. 자동차 수 만큼의 랜덤 숫자를 뽑아 리스트를 만든 뒤, 인자로 넘겨주기

이런식인데 ... 조언 부탁드립니당 🥹

2024-02-17 14:34 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
>      }
그리고 `Car.toString()` 관련하여 질문이 있습니다!
데이터의 정보들을 출력하는 형식을 정하는 것은 outputView에 책임이 있을 것 같은데, `toString`을 사용해서 출력 형식을 정하는 것이 일반적인지 궁금합니다! (저는 더 편하고 가독성이 좋다고 생각해서 `toString` 을 사용했습니다)

2024-02-17 14:34 UTC, JoYehyun99 commented on src/main/kotlin/racingcar/utils/InputExceptions.kt
> +        ) { MESSAGE_ERROR_CAR_NAME_INPUT }
넵! 답변 감사합니다 ㅎㅎ

2024-02-17 16:10 UTC, ghojeong commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
>      }
> 데이터의 정보들을 출력하는 형식을 정하는 것은 outputView에 책임이 있을 것 같은데, toString을 사용해서 출력 형식을 정하는 것이 일반적인지 궁금합니다!

outputView 에 책임이 있다고 생각하신다면, outputView 로 옮겨서 출력에 대한 테스트를 굳이 하지 않는 방법도 있습니다.
만약 백엔드 개발자 과정이라면, 출력 부분을 엄격하게 outputView 로 옮겨달라고 하겠지만, 저희는 안드로이드 과정입니다.

안드로이드 개발을 하다보면, 모델의 상태와 동작을 넘어서, UI 가 제대로 렌더링 되었는지 테스트 하는 경우도 많으므로,
toString 에 대해서는 예니 님이 편하신 대로 해주시면 좋을 것 같습니다.

2024-02-17 16:26 UTC, ghojeong commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
>      }
> 이런식인데 ... 조언 부탁드립니당 🥹

자동차 경주 미션에서 학습하시게 될 핵심 내용 중 하나는,
대체 왜 현업에서 개발자들이 테스트 짜는 것을 어려워할까? 입니다.

지금 같은 상황에서 테스트를 어렵게 하는 요소는 "랜덤" 숫자 입니다.
만약 정해진 숫자가 나온다면 race() 함수 호출 후의 상태 변화 혹은 결과가 예측되기 때문에,
테스트를 쉽게 작성할 수 있습니다.

그리고 조금 더 깊게 생각을 해본다면, 테스트의 결과가 예측하기 어려운 이유는 랜덤 때문이 아닙니다.
[알고리즘으로 동작하는 컴퓨터에 랜덤은 존재하지 않기](https://youtu.be/mYcS9oBgdck) 때문입니다.

랜덤이 존재하지 않는 컴퓨터 알고리즘 혹은 프로그램에서, 프로그램의 동작 결과를 알기 어려운 보다 근본적인 이유는,
NumberGenerator object 가 사용하고 있는 `.random()` 메서드를 예니 님이 구현한게 아니라,
예니 님이 구현하지 않은 외부 라이브러리이기 때문이라서 그렇습니다.

만약 예니 님이 외부 라이브러리에서 제공하는 random() 함수의 소스코드를 모두 읽고,
그 알고리즘을 전부 이해한다면, 프로그램의 동작을 예측하고 테스트 코드를 짤 수 있습니다.

그러나, 그러면 테스트 주도 개발을 하려면 외부 라이브러리를 쓸 때마다, 그 소스코드를 모두 읽고 공부해야하는 걸까요?
안드로이드 개발을 하면 안드로이드 프레임워크와 수많은 라이브러리들을 공부해야할텐데,
그걸 다 공부할 수는 있을까요? (사실 안드로이드 개발자로 경력이 쌓일 수록, 언젠가는 공부해야 하기는 합니다.)

많은 개발자들이 이러한 이유로 프레임워크 혹은 라이브러리를 써야만 하는,
현업 개발을 할 때 테스트 주도 개발을 포기합니다.

가장 무식한 해결책은 race() public 메서드를 모델이 아니라, controller 로 옮겨버리고 테스트를 하지 않는 것입니다.
그리고 시간이 없을 때는 그렇게 하는 것도 괜찮습니다.

하지만, 혹시 예니 님이 도전을 해보고 싶다면 !!!! 
race() 메서드가 `.random()` 에 의존하지 않도록 의존성을 분리하는 작업을 해보시라고 조언드립니다.

2024-02-18 05:52 UTC, ghojeong requested changes
작업해주신 내용에 대해 부연 설명과, 공부하면 좋을 키워드들을 달아보았습니다.
제가 새롭게 제시한 키워드들 중에 모르는게 있다면 추가로 공부해보시고,
마지막으로 코드를 다듬어 주시기 바랍니다.
만약 예니님이 스스로 보기에 충분히 만족스러우시다면, 자동차 미션은 여기서 마무리 하도록 하겠습니다.

아참, jvmTarget 을 19로 바꾸어두신듯 한데 17로 해주시기 바랍니다.
만약 본인의 컴퓨터 개발환경 때문에 바꾼 거라면, 앞으로의 미션에 계속 지장이 있을 수 있으므로,
프로젝트의 jvmTarget 이 아니라 예니님의 개발환경을 바꾸어주시기 바랍니다.

2024-02-18 05:52 UTC, ghojeong commented on src/main/kotlin/racingcar/model/Car.kt
> +        require(name.length <= CAR_NAME_LENGTH) { MESSAGE_ERROR_CAR_NAME }
Car 이름에 대한 validation 을 Car 객체에서 하니 무척 자연스러워보입니다. 👍

2024-02-18 05:52 UTC, ghojeong commented on src/main/kotlin/racingcar/model/Car.kt
> +        const val MESSAGE_ERROR_CAR_NAME = "자동차 이름은 5글자를 초과할 수 없습니다."
Car 이름과 관련 예외 상수값들이 Car 내부에 하나로 모여있으니,
응집성도 올라갔다는 생각이 드네요. 👍

2024-02-18 05:52 UTC, ghojeong commented on src/main/kotlin/racingcar/model/RacingCarGame.kt
> +    fun race(getNumber:() -> Int): List<Car> = List(cars.size) { index -> move(index, getNumber()) }
매우 훌륭합니다. 👍 💯 
제 의도와 100% 일치합니다.

[전략 패턴](https://refactoring.guru/ko/design-patterns/strategy) 이라는 디자인 패턴에 대해서도 추가로 공부해보세요.

객체지향에 익숙한 사람들은 이를 [Functional Interface](https://www.baeldung.com/java-8-functional-interfaces) 를 통해 추상화 했다는 표현을 사용하고,
함수형 프로그래밍에 익숙한 사람들은 이를 [Higher-order function](https://kotlinlang.org/docs/lambdas.html) 을 통해 추상화를 했다고 표현합니다.

이번 기회에 추상화가 용어만 어렵지, 실제로는 그렇게 어려운게 아니라는 것을 느꼈다면 제대로 학습하셨다고 생각합니다.

2024-02-18 05:52 UTC, ghojeong commented on src/test/kotlin/racingcar/model/RacingCarGameTest.kt
> +        val result = racingCarGame.race { numbers.removeAt(0) }
getNumber 를 추상화 함으로서, 랜덤이 아닌 시나리오에 따른 숫자를 출력할 수 있게 되었습니다.
이렇게 자신이 통제할 수 있는 외부 라이브러리를, 자신이 통제할 수 있는 구현체로 흉내(Mocking)내는 것이 테스트 주도 개발을 하기 위한 핵심적인 역량 중 하나입니다.
앞으로의 모든 미션에서 이러한 연습을 많이 해보시기 바랍니다.

2024-02-19 01:23 UTC, ghojeong approved these changes
예니 님!
혼자 해결하기 어려운 피드백일 수도 있었는데,
훌륭하게 스스로 생각해 내주셨습니다. 👍 

전략 패턴을 말씀드렸지만, 디자인 패턴은 수많은 방법중에 하나일 뿐,
추상화가 무엇인지 왜 중요한지를 잊지마시고 앞으로의 미션 헤쳐나가기를 응원합니다. 🔥 
언젠가 예니 패턴과 같이 본인만의 디자인 패턴을 만들어 보시는 것도 기대하겠습니다. 😄

2024-02-19 01:23 UTC, merged