[자동차 경주 구현] 채드 미션 제출합니다.
woowacourse/kotlin-racingcar pull request #112
Opened 2024-02-16 17:05 UTC by dpcks0509

## step2 미션 제출
안녕하세요 안드로이기 6기 채드입니다!
부족한 실력이지만 리뷰 잘 부탁드립니다!

---
❓질문
- domain 로직을 구분하는 기준이 궁금합니다. 저의 코드에서는 model 패키지의 Car , racingGame 클래스 2개만이 domain 로직에 해당되는 것이 맞을까요?
- Car 클래스에서 랜덤함수를 생성하는 함수를 Controller 클래스로 분리를 시켜서 랜덤숫자에 대한 값을 테스트 코드에서 임의로 지정할 수 있는 방법을 찾지못하여 레이싱게임을 1라운드 진행했을때 모든 자동차들의 위치가 0과~1사이에 위치하는지 확인하는 테스트 코드로 대체를 하였는데 올바른 방법인지 궁금합니다.

2024-02-17 06:00 UTC, vagabond95 requested changes
이전 단계에서 View, Controller, Model 을 잘 분리해주셔서 구조적으로는 크게 코멘트를 남길 부분이 보이지 않았어요 👍 

추가로 남긴 코멘트를 참고하여 개선 후 리뷰요청 부탁드릴게요!

2024-02-17 06:00 UTC, vagabond95 commented on src/main/kotlin/racingcar/controller/CarController.kt
>          val winners = racingGame
이전보다 controller 코드가 간결해졌네요 👍

2024-02-17 06:00 UTC, vagabond95 commented on src/main/kotlin/racingcar/controller/CarController.kt
>      private fun endRacingGame() {
end 라는 의미가 조금 모호한 것 같아요,
가령, judgeWinners 라는 동작도 `progressRacingGame` 에 포함된다고 생각할 수 있지 않을까요?

제가 드리고 싶은 이야기의 핵심은 해당 함수에 2가지 이상의 동작이 수행되고 있고 그것이 end 라는 이름으로 묶여있기에,
해당 함수의 역할이 모호하고 비대해질 수 있는 신호를 가지고 있다고 생각해요.

2024-02-17 06:00 UTC, vagabond95 commented on src/main/kotlin/racingcar/model/Car.kt
> +        private set
외부에서 상태 변경이 불가능하도록 처리 👍

2024-02-17 06:00 UTC, vagabond95 commented on src/main/kotlin/racingcar/controller/CarController.kt
>          val winners = racingGame
이 부분도, racingGame 에서 winners 까지 만들어서 넘겨주는 것은 어떨까요?
Controller 에서는 최대한 실제로 동작하는 비즈니스 로직은 알지 못하고 domain 과 view 를 연결해주는 코드만 넣어준다고 생각해보면 좋을 것 같아요.

2024-02-17 06:00 UTC, vagabond95 commented on src/test/kotlin/racingcar/RacingGameTest.kt
> +        repeat(5) {
PR 에도 적어주셨지만, 랜덤값으로는 정확한 테스트 결과를 보장할 수 없기 때문에 이렇게 수동으로 move 처리를 해주신 것 같아요.

저는 이러한 접근 방법도 좋다고 생각합니다. 👍 

결국 우리가 궁극적으로 초점을 맞춰야 할 부분은 '랜덤으로 움직이는 것' 이 아니라,
1) 자동차가 움직일 수 있고, 2) 정해진 값 이상을 움직였을 때 우승자로 판단할 수 있느냐니까요.

그렇다면,
1) 항목은 `올바른 차 전진 테스트` 코드를 통해서 검증이 되었고,
남은 것은 2) 항목이네요!

한번 생각을 바꿔볼께요. 랜덤하게 움직이는 것이 문제라면, `움직이는 방식을 변경`해볼수도 있지 않을까요? 

위에서 작성해주신 것을 조금 더 유연하게 코드로 풀어보는 방법이 있을 것 같아요.
[전략 패턴](https://victorydntmd.tistory.com/292) 이라는 키워드가 도움이 되실 것 같습니다 :)

2024-02-17 06:02 UTC, vagabond95 commented
> domain 로직을 구분하는 기준이 궁금합니다. 저의 코드에서는 model 패키지의 Car , racingGame 클래스 2개만이 domain 로직에 해당되는 것이 맞을까요?

도메인이라는 것이 추상적이고 넓은 범위의 개념이라 무엇이다! 라고 이해하기가 참 어려운 것 같아요.
제가 이해하는 도메인이란, `주어진 프로그램의 목적을 달성하기 위해 핵심적인 동작을 수행하는 영역`인데요. 
다른 것은 대체 가능하지만, 이 코드가 없으면 프로그램이 의미가 없어진다. 라고도 볼 수 있습니다.

우선 현재 단계에서는 view 와 controller 를 제외한 모든 것 이라고 이해해주셔도 좋을 것 같습니다~!

2024-02-18 16:52 UTC, dpcks0509 commented on src/test/kotlin/racingcar/RacingGameTest.kt
> +        repeat(5) {
저는 모든 라운드가 끝났을때 가장 많은 이동을 한 자동차가 우승자가 되는 것으로 이해를 하여서,
 "2) 정해진 값 이상을 움직였을 때 우승자로 판단" 이 부분을 어떻게 처리해야 할지 모르겠습니다. 🥲

2024-02-19 06:31 UTC, vagabond95 requested changes
RacingGame 테스트와 관련하여 궁금하셨던 부분에 대해 추가로 코멘트를 남겼어요!
현재 단계에서 필수로 반영되어야하는 것은 아니고, 마무리하고 싶다면 다음 미션에서 고민해주셔도 괜찮습니다.

마지막까지 화이팅이십니다~!

2024-02-19 06:31 UTC, vagabond95 commented on src/test/kotlin/racingcar/RacingGameTest.kt
> +            carOfPobi.moveCar()
조금 더 풀어서 이야기를 나누어봐요 :)

현재 racingGame 에서 주요하게 테스트해야하는 부분은 
얘기해주신 것처럼 "가장 많은 이동을 한 자동차가 우승"하는 것이에요.

그런데, 요구사항에 비추어보면 자동차는 매번 랜덤한 값에 의해 움직임이 결정되므로
원하는 시나리오로 테스트를 할 수가 없는 상황이에요.

그래서 carOfXX 와 같이 직접 car 를 수동으로 움직여서 우승자를 만들도록 코드를 작성해주셨구요!

그런데, 이 코드는 car 를 직접 제어했기 때문에, `racingGame` 이 정말로 그렇게 동작하는지는 검증할 수 없어요. CarTest 를 다시 반복한 것에 가까워요.

결국 racingGame 을 검증하려면 racingGame 을 직접 제어하고, 이로부터 나온 결과를 활용하여 테스트를 돌려야합니다.

2024-02-19 06:31 UTC, vagabond95 commented on src/test/kotlin/racingcar/RacingGameTest.kt
> +            carOfPobi.moveCar()
여기까지 이해가 되셨다면 남은 문제는 "랜덤하게 움직이는 차" 라는 조건입니다.
랜덤이 테스트하기 어려운 영역임을 확인하셨으니, 랜덤하지 않게 움직이도록 변경하면 되지 않을까요?

현재는 RacingGame 코드가 움직임을 제어하는 부분을 외부에서 변경이 불가능하지만,
위에서 공유드린 전략패턴을 활용한다면 변경 가능하도록 리펙토링 해볼 수 있을 것 같아요.

리펙토링이 완료되면, 테스트 코드에서는 "내가 원하는 대로 움직이는" RacingGame 을 테스트해볼 수 있겠죠 :)

2024-02-19 13:38 UTC, vagabond95 approved these changes
다소 모호할 수 있는 주제인데, 끝까지 개선을 위해 시도하시는 모습 좋습니다 👍 
현 단계에서 추가적으로 드릴 수 있는 코멘트는 없는 것 같습니다.
(그동안 남겼던 코멘트 내용에 대해 추가적으로 논의하고 싶은 부분 있다면 편하게 DM 주세요~!)

다음 미션도 화이팅 이십니다 👍

2024-02-19 13:38 UTC, vagabond95 commented on src/main/kotlin/racingcar/model/RacingGame.kt
> +) : MoveStrategy {
인터페이스를 통해 좀 더 느슨한 연결이 될 수 있도록 시도해주셨네요 👍 

그런데, 인터페이스의 구현체가 RacingGame 하나이기 때문에 인터페이스를 사용했을 때의 이점이 크게 없는 것 같아요.
😢 
RacingGame 이 MoveStrategy 를 구현하기보다, racingCar 함수에서 MoveStrategy 를 `주입`받는 구조였으면 더 좋았을 것 같아요. 이 부분은 1단계에서 중요한 부분은 아니라고 생각되어, 여기서 논의를 마무리하겠습니다. 

다음 미션 진행시에도 한번쯤 고려해주시면 좋겠습니다~!

2024-02-19 13:38 UTC, merged