[크롱] 코틀린 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #34
Opened 2023-02-09 06:13 UTC by krrong

많이 배워가는 시간이었습니당😊

2023-02-09 16:03 UTC, galcyurio requested changes
첫 번째 미션 진행 고생하셨습니다 :+1: 
몇 가지 코멘트를 남겨두었으니 확인 후 반영해주세요.

2023-02-09 16:03 UTC, galcyurio commented on docs/README.md
> +# domain
> InputView 클래스에서 자동차의 이름과 시도할 횟수를 입력받는 함수명을 짓는데 좋은 방법이 있을까요?

이름을 짓는 건 여러 코드를 많이 살펴보고 머리에 익혀두시면 좋습니다.
보통은 도메인에 어울리는 네이밍으로 지으시는게 가장 좋습니다.
https://grep.app 과 같은 사이트를 이용해서 어떤 네이밍이 자주 쓰이는지 확인하실 수 있습니다.

지금처럼 입력을 받는 함수의 경우에는 아래와 같은 네이밍을 추천드려요.
- awaitXxx(): 쓰레드가 block되므로 가장 잘 어울린다고 생각해요.
- getXxx()
- inputXxx()
- receiveXxx()

2023-02-09 16:03 UTC, galcyurio commented on docs/README.md
> +# domain
> 예외처리를 여러 곳에서 진행하는데(Car, RacingManager) 이런 경우 각 클래스에서 예외를 처리하는 방법과 예외처리 클래스를 만들고 메서드로 사용하는 방법 중에서 더 효율적인 방법은 어떤 것일까요?

Car, RacingManager에는 예외처리 코드(try-catch)가 보이지 않네요. 예외를 던지는걸 말씀하시는걸까요?
저는 아래와 같이 시도해보는걸 추천드려요.

- [논리 오류](https://ko.wikipedia.org/wiki/%EB%85%BC%EB%A6%AC_%EC%98%A4%EB%A5%98)일 때만 예외를 던지세요.
- 논리 오류가 아니면 예외를 던지지 말고 null을 반환하세요.
- 실패하는 경우가 복잡해서 null로 처리할 수 없으면 sealed class를 반환하세요.
- 일반적인 코틀린 코드에서 `try-catch`를 사용하지 마세요.

위 사항들의 자세한 설명은 아래 글을 읽어보세요.
https://medium.com/@elizarov/kotlin-and-exceptions-8062f589d07

2023-02-09 16:03 UTC, galcyurio commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun plusLocation(num: Int) {
이 함수는 차량이 움직이는 책임을 가지고 있네요.
움직인다는 점을 함수명에 드러내보면 어떨까요?

2023-02-09 16:03 UTC, galcyurio commented on src/main/kotlin/racingcar/domain/NumberGenerator.kt
> +    fun generateNumber(MIN_NUMBER: Int, MAX_NUMBER: Int): Int
https://kotlinlang.org/docs/coding-conventions.html#functions
코틀린 컨벤션에 따라 매개변수명은 camelCase로 지어주세요.

2023-02-09 16:03 UTC, galcyurio commented on src/main/kotlin/racingcar/view/OutputView.kt
> +        println(carName + " : " + "-".repeat(carLocation))
String template 기능을 활용해보세요.
https://www.baeldung.com/kotlin/string-templates

2023-02-09 16:03 UTC, galcyurio commented on src/main/kotlin/racingcar/controller/GameController.kt
> +    private lateinit var racingManager: RacingManager
`lazy()`와 `lateinit var`는 어떤 차이가 있고 각각 어느 상황에서 사용하면 좋을까요?
https://stackoverflow.com/questions/36623177/property-initialization-using-by-lazy-vs-lateinit

2023-02-09 16:03 UTC, galcyurio commented on src/main/kotlin/racingcar/resources/String.kt
> +const val ERROR_NAME_LENGTH_RANGE = ERROR_MESSAGE_PREFIX + "자동차 이름은 1~5자 사이어야 합니다."
상수는 한 곳에 모으기 보다는 연관이 있는 파일에 같이 두는게 좋습니다.
여러 곳에서 쓰이는 경우가 아니면 해당 클래스의 companion object에 선언해보세요.

2023-02-10 05:41 UTC, krrong commented on src/main/kotlin/racingcar/resources/String.kt
> +const val ERROR_NAME_LENGTH_RANGE = ERROR_MESSAGE_PREFIX + "자동차 이름은 1~5자 사이어야 합니다."
여러 곳에서 사용되는 `ERROR_MESSAGE_PREFIX`를 제외한 나머지 상수들은 각각 사용하는 클래스의 companion object로 이동하여 반영하였습니다 :)

2023-02-10 11:11 UTC, krrong commented on src/main/kotlin/racingcar/domain/Car.kt
> +    fun plusLocation(num: Int) {
함수명 move로 변경하여 반영하였습니다 :)

2023-02-10 11:13 UTC, krrong commented on src/main/kotlin/racingcar/domain/NumberGenerator.kt
> +    fun generateNumber(MIN_NUMBER: Int, MAX_NUMBER: Int): Int
camelCase로 변경하여 반영하였습니다 :)

2023-02-10 11:15 UTC, krrong commented on src/main/kotlin/racingcar/view/OutputView.kt
> +        println(carName + " : " + "-".repeat(carLocation))
String template을 활용하여 적용하였습니다 :)

2023-02-10 11:34 UTC, krrong commented on docs/README.md
> +# domain
제가 질문을 명확하지 않게 했던 것 같아요! 예외를 던지는 것을 여쭤봤던 것입니다ㅎㅎ

그리고 한 가지 추가적으로 질문이 생겼는데 InputView에서 데이터를 입력 받고 Car 객체를 생성할 때 인자로 이름을 넘겨줍니다. 그러면 이 때 값의 유효성 검증을 어느 부분에서 하는 게 더 좋은(효율적인) 방법인지 고민입니다.

가능한 방법은
1. Car객체를 생성할 때 값의 유효성 검증을 한다.
2. InputView에서 입력을 받을 때 유효성 검증을 한다.
3. 1, 2를 같이 진행한다.
가 있을 것 같다고 생각이 됩니다. 그 중에서도 저는 InputView 에서 처리를 하고 Car객체에 넘겨주는 방식이 좋을 것 같다고 생각되는데 리뷰어님의 생각도 궁금합니다!

2023-02-10 12:29 UTC, krrong commented on src/main/kotlin/racingcar/controller/GameController.kt
> +    private lateinit var racingManager: RacingManager
`lateinit var`는 초기화 이후 값의 변경이 필요할 경우에 사용하며 `lazy()` 는 초기화 이후 값을 변경하지 않을 때 사용하며 프로퍼티를 초기화 한 이후 읽기 전용으로 사용할 때 쓰는 것으로 이해했습니다! 

그래서 `GameController`를 생성할 때 `RacingManager`를 주입 받아 생성될 수 있도록 코드를 수정했습니다.
위 방식을 진행하면서 든 의문인데 위 내용은 `InputView`와 `OutputView`에도 마찬가지라고 생각이 되는데 이 경우에는 `by lazy()`를 통해서 나중에 사용할 때 초기화 하는 것이 좋을까요, 아니면 외부에서 주입받아 사용하는 것이 더 좋을까요?

2023-02-11 05:29 UTC, galcyurio approved these changes
1단계 미션 고생하셨습니다 🙂 
질문에 대한 답과 추가적인 피드백을 코멘트로 남겨두었으니 확인해주세요.
피드백 반영은 다음 단계에서 같이 진행해주시면 됩니다.

2023-02-11 05:29 UTC, galcyurio commented on src/main/kotlin/racingcar/controller/GameController.kt
> +    private lateinit var racingManager: RacingManager
> 그래서 GameController를 생성할 때 RacingManager를 주입 받아 생성될 수 있도록 코드를 수정했습니다.
위 방식을 진행하면서 든 의문인데 위 내용은 InputView와 OutputView에도 마찬가지라고 생각이 되는데 이 경우에는 by lazy()를 통해서 나중에 사용할 때 초기화 하는 것이 좋을까요, 아니면 외부에서 주입받아 사용하는 것이 더 좋을까요?

Controller에서 View를 생성한다는 것은 View에 의존한다는 것과 같습니다.
예를 들면, Android 또는 Swing과 같은 플랫폼에 의존하게 되는 것입니다.

더 엄격하게 UI에 대한 의존성을 분리하기 위해서는 View를 interface로 분리하고 구현체를 생성자로 주입받는 것이 더 좋습니다.
그렇게 해야 UI와 관련된 의존성이 분리되기 때문에 Controller에 대해 단위테스트가 가능해집니다.

2023-02-11 05:29 UTC, galcyurio commented on docs/README.md
> +# domain
때에 따라 1번, 2번을 섞어서 쓰는 편인데 저도 주로 2번 방식을 선호하는 편입니다.

판단 방식은 주로 "유효성 검사가 도메인 로직이냐? 아니냐?"와 같은 질문을 던져보고 맞다면 1번처럼 domain으로 분류하고 아니라면 2번처럼 UI 단에서 처리합니다.

다만, 도메인 로직인지 아닌지에 대한 판단은 개발자마다 다를 수 있어서 저 또한 팀원들이랑 코드리뷰를 하면서 기준이 바뀌기도 합니다.

이 부분은 저도 명확하게 답변을 드리기가 쉽지 않네요 😓

2023-02-11 05:29 UTC, galcyurio commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    }
print 대신 결과를 반환 👍

2023-02-11 05:29 UTC, galcyurio commented on src/main/kotlin/racingcar/domain/Car.kt
> +        require(condition in MIN_BOUNDARY..MAX_BOUNDARY) { ERROR_INPUT_COUNT }
유효성 검사와 관련된 질문에 이은 추가 답변입니다.
이런 경우에는 보통 `숫자는 0부터 9까지만 입력할 수 있습니다.` 에러 메시지를 보여주고 다시 입력받아야 한다는 요구사항이 주어집니다.

하지만 이미 Car 객체의 `move()` 함수까지 들어와버렸으니 여기서 처리하기 위해서는 Exception을 던지거나 Result 객체를 반환해서 복잡하게 처리해야 합니다.
이런 상황에서는 domain 객체 대신에 UI 객체에서 처리한다면 조금 더 간단하지 않을까요?

2023-02-11 05:29 UTC, galcyurio commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    private var cars: List<Car> = _cars
이러한 패턴은 주로 read-only List를 외부에 공개해주기 위한 경우에 작성합니다.
지금은 외부로 공개하지 않으니 `_cars: MutableList`를 `cars`로 그대로 선언해서 사용해도 됩니다.

2023-02-11 05:30 UTC, merged

2023-02-12 13:29 UTC, krrong commented on src/main/kotlin/racingcar/domain/RaceManager.kt
> +    private var cars: List<Car> = _cars
`private var cars = MutableList(0) { Car("") }` 로 반영하였습니다 :)

2023-02-12 14:44 UTC, krrong commented on src/main/kotlin/racingcar/controller/GameController.kt
> +    private lateinit var racingManager: RacingManager
말씀하신대로 UI에 대한 의존성 분리를 위해 View를 interface로 분리하고 생성자로 주입하였습니다. 이후 GameController의 `runGame()`단위 테스트까지 진행했습니다.

그리고 기존의 private으로 선언된 함수들을 테스트를 위해 public으로 바꾸는 것은 좋지 않은 것일지 의문이 듭니다!

2023-02-12 14:54 UTC, krrong commented on docs/README.md
> +# domain
자세하게 말씀해주셔서 감사합니다! 덕분에 잘 이해된 것 같아요 :)

2023-02-12 14:57 UTC, krrong commented on src/main/kotlin/racingcar/domain/Car.kt
> +        require(condition in MIN_BOUNDARY..MAX_BOUNDARY) { ERROR_INPUT_COUNT }
어떤 느낌인지 이해한 것 같습니다 :)

그런데 현재 `move()`함수에서 필요한 condition은 `numberGenerator`를 통해 생성하고 전달 받습니다. 그렇다면 이런 과정에서 값의 유효성 처리는 RaceManager에서 하고 다시 입력 받도록 하는 것이 좋다고 생각되는데 그렇게 진행해도 역할 분리가 잘 되었다고 말할 수 있을지 궁금합니다!