[우기] 코틀린 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #35
Opened 2023-02-09 06:35 UTC by boogi-woogi

혼자 코딩하다 보면 다양한 방법을 생각하기 힘든데 페어와 함께 하다보니 이전에 사용하지 못했던 것들로 새롭게 코딩을 하는 경험을 할 수 있었습니다.

2023-02-09 10:51 UTC, woowajames requested changes
우기 안녕하세요! 리뷰를 맡게 된 제임스입니다. 반가워요. 😊
자동차 경주 미션 1단계 구현 잘해주셨습니다. 굿굿!
몇 가지 코멘트를 남겼는데 확인 부탁드려요. 어려운 부분이나 궁금하신 사항이 있으시면 언제든지 편하게 DM 주세요. 24시간 아무 때나 DM 주셔도 됩니다.

2023-02-09 10:51 UTC, woowajames commented on README.md
> +- 우승자 출력
기능 목록 작성 좋습니다! 👍
기능 목록을 좀 더 고민하면 목록이 commit 단위가 될 수 있고 테스트 코드 작성에도 많은 도움이 되실거에요! 다음에는 좀 더 상세하게 적도록 도전해보세요. 💪

2023-02-09 10:51 UTC, woowajames commented on README.md
> +- 테스트 코드 작성하기
완료 하셨으면 지우셔도 될거 같습니다. 🙂

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/Application.kt
> +    carRacingGameController.startGame()
단순히 startGame()을 호출한다면 굳이 컨트롤러를 별도로 둘 필요가 있을까요?

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/util/Constants.kt
> +const val STOP_MARK = ""
Constants 클래스를 만들어서 사용하셨네요. 이런 방법도 있지만 이렇게 사용하면 불필요한 결합도가 증가하게 됩니다. 결합도가 증가한다는건 여기 있는 상수를 쓰고 있는 클래스가 자신의 기능에 충실하기 어렵다는걸 의미하기도 해요. 단일 개념이 단일 클래스에 포함되면 그 개념과 관련된 요구 사항을 수정할 때 해당 클래스만 수정하면 되니까 효율적이겠죠?

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/data/CarPath.kt
> +data class CarPath(
data class 사용 굿 👍

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/data/Car.kt
> +        require(name.length <= 5) {
매직 넘버는 상수화 하면 어떤 역할인지 알기 쉽습니다.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/view/View.kt
> +}
해당 object는 불필요한 것 같습니다. 굳이 이렇게 사용하신 이유가 있으신가요?

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/view/InputView.kt
> +        return br.readLine()
readLine()만으로 충분할 것 같네요.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/util/Extension.kt
> +fun List<PathState>.getPathMarks(): String {
util과 같은 클래스는 지양하는게 어떨까요? 사용하기엔 편리하겠지만 이렇게 사용하면 결합도가 증가될 확률이 높습니다. 클래스명도 모호합니다. 🙃 그리고 util로 분류했지만 결국 도메인에 포함될 것으로 보이고 그렇게 되면 현재 도메인과 뷰에 의존성이 생깁니다.

2023-02-09 10:51 UTC, woowajames commented on src/test/kotlin/CarTest.kt
> +    }
이미 List로 변환이 잘되었다는 가정하에 진행된 테스트로 보입니다. 기능 요구 사항엔 없는 내용이지만 만약 이름은 최소 1자 이상이어야 한다는 식의 조건이 추가된다면, 다시 말해서 "a,,b,c" 와 같은 String 입력은 어떻게 검증이 될까요? 이 상황을 검증 하라는 의미는 아니고 기능 목록 '쉼표 기준 구분'에 대한 검증이 보이지 않습니다.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/domain/CarRacingGameController.kt
> +    }
하나의 메서드에서 입력 받은 이름을 나누는 일과 Cars를 생성하는 일을 하고 있네요. 이름을 나누는 역할을 어디서 하면 좋을까요? 🙂

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/domain/CarRacingGameController.kt
> +        return numberOfTry.toInt()
검증을 하기 위한 메서드를 호출하고 있네요. 검증이 완료되면 Int로 변환하면 바로 받을 수 있지 않을까요? 그러면 매번 Int로 변환하는 코드를 작성할 필요가 없어지기도 합니다. 😀

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/view/InputView.kt
> +object InputView {
object 굿 🥳

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/domain/CarRacingGameController.kt
> +        }
for문 대신 repeat 사용 좋습니다! 다만 해당 로직은 View를 위한 로직이네요. View에게 해당 역할을 맡기면 어떨까요?

2023-02-09 10:51 UTC, woowajames commented on src/test/kotlin/InputValidatorTest.kt
> +    @ValueSource(strings = ["a", "세번", "다섯", "-3"])
다양한 값으로 테스트 한 것 좋습니다! 굳이 말씀드리자면 한글 두 번 보다는 특수문자를 하나 넣었다면 좀 더 다양한 케이스가 되지 않을까 싶어요.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/data/generator/NumberGenerator.kt
> +interface NumberGenerator {
해당 인터페이스가 있을 때의 장점이 무엇이 있을까요? 제 생각에는 테스트를 위해서 추가된 게 아닌가 싶어요.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/data/generator/RacingNumberGenerator.kt
> +    }
IntRange 형태의 매직 넘버도 상수화 하면 의미가 좀 더 명확해집니다.

2023-02-09 10:51 UTC, woowajames commented on src/test/kotlin/CarMovingTest.kt
> +    }
이러한 클래스 없이 동일한 테스트를 할 수 없을까요?

힌트 : 테스트 하고자 하는 값을 메서드로 주입 받는다.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/domain/CarRacingGame.kt
> +class CarRacingGame {
이 클래스에 대한 테스트 코드가 없습니다. 따라서 기능 목록에 작성된 '우승자 출력' 부분 검증이 되지 않습니다. UI 검증이 아니라 우승자가 제대로 선정 되었는지에 관한 테스트를 말씀드리는거에요.

2023-02-09 10:51 UTC, woowajames commented on src/main/kotlin/domain/CarRacingGameController.kt
> +class CarRacingGameController(
추후에 배우시게 되겠지만 컨트롤러는 도메인이 아닌 별도로 분리가 되어야 합니다. 수정을 하라는 의미가 아니라 참고로 말씀드려요!

2023-02-09 11:17 UTC, boogi-woogi commented on README.md
> +- 우승자 출력
넵 다음 단계부터는 더욱 더 상세하게 적도록 노력하겠습니다!

2023-02-09 11:19 UTC, boogi-woogi commented on src/test/kotlin/CarMovingTest.kt
> +    }
그 방법은 생각하지 못했었는데 다음 단계에서 바로 수정하겠습니다!

2023-02-09 11:25 UTC, boogi-woogi commented on src/main/kotlin/view/View.kt
> +}
inputView와 outputView 각각 bufferedReader와 bufferedWriter를 가지는 것보다 하나를 생성해놓고 그것을 공유하여 사용하면 더욱 효율적일 것이라고 생각했는데 수정하겠습니다!

2023-02-09 11:37 UTC, boogi-woogi commented on README.md
> +- 테스트 코드 작성하기
바로 수정하겠습니다😀

2023-02-09 11:39 UTC, boogi-woogi commented on src/main/kotlin/util/Constants.kt
> +const val STOP_MARK = ""
해당 const들을 관련있는 클래스에 포함되도록 수정하겠습니다😁

2023-02-09 11:41 UTC, boogi-woogi commented on src/main/kotlin/data/Car.kt
> +        require(name.length <= 5) {
바로 반영해서 수정하겠습니다!!

2023-02-09 11:42 UTC, boogi-woogi commented on src/main/kotlin/data/generator/RacingNumberGenerator.kt
> +    }
수정하겠습니다!!

2023-02-09 12:17 UTC, boogi-woogi commented on src/main/kotlin/util/Extension.kt
> +fun List<PathState>.getPathMarks(): String {
해당 부분도 관련있는 클래스에 속할 수 있도록 수정하겠습니다!

2023-02-09 12:50 UTC, woowajames commented on src/main/kotlin/view/View.kt
> +}
지금 수준의 미션에서는 버퍼를 써야할만큼 성능에 대해 고려할 필요는 없다고 생각해요. readLine()만으로 충분할 것 같아요.

2023-02-11 04:40 UTC, woowajames requested changes
피드백 반영하시느라 수고 많으셨습니다!
몇 가지 코멘트 남겼는데 확인 하시고 다음 단계 진행하면서 충분히 고민해보세요!
다음 단계 진행을 위해 머지하겠습니다!

2023-02-11 04:40 UTC, woowajames commented on src/test/kotlin/InputValidatorTest.kt
> +    }
예외 발생하는 경우에 대한 테스트도 좋지만 기본 기능이 정상적으로 동작 하는지에 대한 테스트가 우선되어야 하지 않을까 싶습니다. 제대로 나눠지고 있는지 검증을 해야합니다.

2023-02-11 04:40 UTC, woowajames commented on src/test/kotlin/WinnerTest.kt
> +                    override fun generate(): Int = RacingNumberGenerator.MINIMUM_NUMBER_TO_MOVE
RacingNumberGenerator에 있는 상수를 이렇게 가져다 쓰는 건 결국 결합도가 높아진 것이 아닐까요? 이 상태에서 3이라는 숫자를 테스트하고 싶으면 상수를 어디에 두어야할 지 고민이 생기지 않나요?

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/domain/RacingNumberGenerator.kt
> +        const val MINIMUM_NUMBER_TO_MOVE = 4
이 클래스 내부에서 쓰지 않는 상수가 왜 있어야 할까요?

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/data/Car.kt
> +        if (racingNumberGenerator.generate() >= MINIMUM_NUMBER_TO_MOVE) {
여기서 쓰는 상수를 왜 다른 클래스에 굳이 의존하고 있을까요? Constants 클래스를 다른 여러 클래스로 나눈 것일 뿐 결국 근본적인 문제는 똑같이 발생하고 있네요.

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/data/InputError.kt
> +}
입력에 관한 것이라면 입력에 대한 역할을 하는 클래스로 옮겨보면 어떨까요?

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/domain/InputValidator.kt
> +}
패키지는 도메인 내에 있지만 여전히 유틸리티성 클래스로 보입니다. 이 로직을 필요로 하는 클래스로 옮길 수 있는 방안을 찾아보세요.

2023-02-11 04:40 UTC, woowajames commented on src/test/kotlin/WinnerTest.kt
> +class WinnerTest {
보통 테스트할 클래스명Test로 하는데 이렇게 CarRacingGame에 있는 기능을 테스트 하기 위해서 테스트 클래스가 분리된다는 것은 CarRacingGame도 두 가지 이상의 역할을 하고 있는게 아닐까요? (CarMovingTest도 마찬가지입니다.)

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/view/OutputView.kt
> +    const val EMPTY = ""
private으로 바꿔보면 다른 곳에서 이 클래스에 접근하고 있는 것들을 수정할 수 있겠네요. 단지 이리저리 가져다 쓰기 편해서 object를 사용하는 것이라면 지양하는 것이 좋습니다.

2023-02-11 04:40 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
> +    private fun initAll(): CarRacingGameDataSource {
All에 무엇이 포함되는지 코드를 처음 보는 사람 입장에서 쉽게 이해가 될까요?

2023-02-11 04:40 UTC, merged