[코비] 코틀린 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #42
Opened 2023-02-09 06:49 UTC by rhkrwngud445

2023-02-09 11:56 UTC, laco-dev requested changes
안녕하세요.
자동차 경주 미션과 함께 하게 되었습니다. 😄 

여러가지 경험하신 부분이 보여서 재미있게 리뷰할 수 있었습니다.

한가지 생각해보시면 좋을만한 점은 테스트 코드의 이름만 봤을때 어떻게 객체가 역할을 하는지 알 수 있을까? 에대해 생각해보시면 좋겠어요.

지금은 이 테스트가 실패했을때 왜 실패했는지, 성공한다면 왜 성공하는지를 다소 알기 어려울 수 있어요.

구조적으로 개선해보면 좋을 만한 내용도 같이 남겨드렸으니 충분히 고민 해 보시고 반영 해주시면 됩니다.

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/Application.kt
> +fun main() {
> feat: 뼈대 코드 작성

기능을 구현하는 과정에서 어떻게 구현을 해 나갈지 모르기 때문에 이러한 커밋 단위는 좋지 않은 방법입니다.
실제로 구현할때 코드가 변경이 될 텐데, 왜 이렇게 만들어지기 시작했는지 작성자 본인 외에는 아무도 알기 어려울 것입니다.

귀찮음을 피하는 것은 커밋으로 해결하는 것이 아닌, 다른 방법을 모색해야 합니다.

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/view/InputView.kt
> +    fun inputCarName(): String {
입력 기능을 먼저 구현 해 주셨네요. 👍🏻 

앞으로 여러가지 도메인을 구현하는 과정에서의, 한 가지 팁이라면 도메인 로직을 먼저 구현해보면 어떨까? 라는 생각을 가지면 좋습니다.

가령, 자동차 이름을 입력받는 기능을 구현한 뒤 자동차 이름이라는 CarName 모델이 생기게 된다면,
InputView의 구현이 따라서 변경이 되야 합니다.
즉 코드를 두번 이상 수정해야 한다는 의미가 될 수 있어요.

꼭 지켜야 하는 규칙은 아니지만, 기회가 된다면 한번 경험해보시면 좋습니다.

2023-02-09 11:56 UTC, laco-dev commented on README.md
> +- 전체 진행 테스트
테스트 리스트는, 별도로 작성되는 개념이 아닙니다.
하나의 기능은 구현 코드와 테스트코드가 합쳐져서 만들어져야 합니다.
마찬가지로 테스트 코드를 별도의 커밋으로 작성하는 것이 아닌 하나의 기능으로 같이 구현해야 합니다.

특정 함수의 이름이나 오류를 직접적으로 명시할 필요 없이, 기능 목록에서 설명하는 것으로 요구사항이 정리될 수 있어야 하겠습니다.

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +    private var maxMoveCount = 0
racingGame과 maxMoveCount라는 값이 멤버 변수로 있을 필요가 있을까요?
하나의 경주에서 필요한 개념이 되지는 않을까요?

멤버 변수로 작성하면 지금 구현에서는 어떤 장점을 가지게 될까요?
또한 멤버 변수가 아니라면 어떻게 필요한 곳에 값을 전달할 수 있을까요?

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +        println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).")
자동차 입력을 받기 위해 콘솔에 출력하는 내용은 InputView (UI)의 관심사로 볼 수 있지 않을까요?

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +        }
코틀린 컬렉션 함수를 사용해서 간단하게 만들 수 있어요.
```kotlin
carNames.map { ... }
```

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +        }
경주가 끝날때까지 게임을 진행하는 것은 RacingGame에서 관리할 수 있지 않을까요?

하지만 이렇게 되면 OutputView에 접근을 할 수 없는 문제가 될 수 있을 것 같아요.
그렇다면, 출력에 필요한 내용들을 한번에 받아오는 방법도 가능할 수 있습니다.
```
val result = racingManager.race()
outputView.printResult(result)
```

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/model/Car.kt
> +    fun move(randomNumber: Int) {
자동차가 움직이기 위해 필요한 값이 랜덤? 이라는 것을 알 필요가 있을까요?
어떤 값이 들어올지 는 바깥에서 결정되기 때문에 randomNumber 대신 적절한 이름으로 변경해보면 어떨까요?

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
initRacing()이지만 실제로는 cars에 계속해서 쌓인다고 볼 수 있지 않을까요?
초기화의 의도와 맞지 않게 동작하지는 않을까요?
그렇다면 이러한 문제가 발생하지 않으려면 어떤 방법을 사용할 수 있을까요?

```kotlin
val racingGame = RacingGame()
racingGame.initRacing(cars)
racingGame.initRacing(cars)
racingGame.initRacing(cars)
...
??????
```

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +        return result.toList()
우승자를 결정하는 알고리즘을 개선해보면 좋겠습니다!

1. 정렬함수를 사용하기 보다는 코틀린에서 제공해주는 함수를 사용 해 보면 어떨까?
2. 조건문을 검사하고 결과를 만드는 코드가 너무 길지는 않을까?

```
가장 멀리 가 있는 자동차는 누구일까?
가장 멀리 가 있는 자동차와 같은 위치를 가진 차들은 누구일까?
```

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
자동차가 실제 움직여야 할 때 이동 가능한 값을 만들어 보면 어떨까요?
지금은 자동차가 움직이기 위한 조건을 사전에 모두 계산을 해야 합니다.

가령, 자동차가 움직이기 위한 조건을 계산하는데 차 한대당 1초가 걸린다고 한다면, 1000대의 자동차를 모두 준비시키는데에만 많은 시간이 소요될 수 있습니다.

디자인 패턴의 전략 패턴을 사용해 보거나, 다른 방법을 시도 해 볼 수 있겠습니다.
```
fun moveCars() {
   cars.forEach { car -> 
      val number  = numberGenerator.generate()
      car.move(number)
   }
}
```

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
랜덤이라는 불확실성이 도메인 로직에 위치하게 되면 테스트를 비롯한 검증이 어려워 지게 됩니다.

신뢰할 수 있는 코드로 만드려면 어떤 방법을 사용할 수 있을까요?
앞서 드린 자동차가 이동하기 위한 조건을 가져오는 방법과 관련이 있습니다.

힌트 : RandomTest domain, 인터페이스, 전략 패턴 등

2023-02-09 11:56 UTC, laco-dev commented on src/main/kotlin/racing/validators/UserInputValidator.kt
> +    }
자동차 이름이 5글자까지 가능한 것과 빈 값이 불가능한 것은 Validator의 역할일까요?
혹은 자동차의 역할일까요?

아래 코드는 과연 잘 동작 할까요? 아니면 실패할까요?
```
val car = Car(name = "")
var car = Car(name = "123456789")
```

2023-02-09 11:56 UTC, laco-dev commented on src/test/kotlin/racing/model/CarTest.kt
> +    fun `랜덤 숫자가 4,5가 나왔을 떄 테스트`() {
자동차가 이동하기 위한 조건이 랜덤 숫자라는 것은 자동차에 필요한 관심사가 아닐 것이라고 앞서 말씀드려 보았어요.

그렇다면 테스트 이름을 보다 명확하게 작성해서 사용하는 사람이 더욱 잘 이해할 수 있도록 도와보면 어떨까요?
```
자동차는 4 이상의 값이면 한칸 앞으로 전진한다.
자동차는 4 미만의 값이면 이동하지 않는다.
```

2023-02-10 07:03 UTC, rhkrwngud445 commented on src/main/kotlin/racing/Application.kt
> +fun main() {
전체적인 틀 코드를 짜 놓는게 편하다고 생각해 이렇게 커밋 단위를 구성했었는데, 다른 사람이 보았을 때 이해하기 어려운 부분이 맞는 것 같습니다.
아래 말씀 주신 domain 로직을 먼저 구성하는 연습으로 해당 피드백 반영해 보겠습니다!

2023-02-11 09:09 UTC, rhkrwngud445 commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
> 자동차가 실제 움직여야 할 때 이동 가능한 값을 만들어 보면 어떨까요?
> 지금은 자동차가 움직이기 위한 조건을 사전에 모두 계산을 해야 합니다.
위 말씀이 조금 이해가 안되어서 질문 드립니다!ㅠ
움직이기 위한 조건을 사전에 계산을 하는 로직을 미리 수행하는 것으로 이해를 했는데, car.move() 이전에 조건 계산을 수행하게 하는 것인지 궁금합니다!

2023-02-11 15:06 UTC, rhkrwngud445 commented on src/main/kotlin/racing/view/InputView.kt
> +    fun inputCarName(): String {
아하! 리팩토링을 하면서 생성자 또는 인자가 자주 바뀌었었는데, 했던대로 하면 InputView도 계속 바꿔줘야 하는 상황이었어요 앞으로 도메인 로직을 먼저 구현해보겠습니다!

2023-02-11 15:10 UTC, rhkrwngud445 commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +    private var maxMoveCount = 0
단순히 Controller에서의 호출의 편리함으로 작성을 했었습니다. 리뷰어님의 말씀대로 racingGame과 maxMoveCount는 하나의 묶음으로 되어야 한다고 생각되어 startRacing() 생성자로 함께 묶여서 호출되도록 수정하였습니다!

2023-02-12 01:46 UTC, laco-dev approved these changes
피드백 반영하느라 고생 많으셨습니다.

코틀린을 학습하는 과정이라서, 여러가지 언어를 배워가면서 지금보다 더욱 개선하실수 있을 것 같아요.

남겨주신 질문 포함해서 몇가지 의견을 추가로 남겼습니다.
전반적으로 구조가 잘 나뉘어져 있어서 다음 미션에서는 큰 수정이 없을 것 같아요.
그 외에 도전해보고 싶은 점이 있다면 해보셔도 좋습니다. 💪🏻

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +            cars.add(Car(it))
map이 어떻게 동작하는지, 예시를 찾아보세요.
그리고 forEach와 map 함수가 어떤 차이를 가지고 있는지 학습 해보세요

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
race()라는 함수만 봤을때 반환타입이 무엇을 의미하는지 예측하기 어려울 수 있어요.
이럴 떄에는 객체를 만들어서 의미를 전달하는 것도 좋은 방법이 될 수 있습니다.

다만 이 개념은, 앞으로 학습해 나가는 과정에서 배우는 내용이라서, 지금은 참고만 해 주시면 될 것 같습니다.
이렇게도 작성 할 수 있다?

```kotlin
class RaceResult(
   private val positionsByRound: Map<Int, List<Int>>
) {
   val getPositionsBy(round: Int): List<Int> { ... }
}
```

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/Car.kt
> +    private var position = 0
코틀린 프로퍼티의 접근자를 이용하면 별도의 getter(), setter) 함수를 만들지 않고도 처리가 가능합니다.
코틀린에서는 기본적으로는 프로퍼티를 잘 활용하면 좋아요!

https://kotlinlang.org/docs/properties.html#backing-fields

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/Car.kt
> +    private fun checkMove(randomNumber: Int) = randomNumber >= CAN_MOVE_MINIMUM
아직 randomNumber라는 이름이 남아있네요!

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
cars를 초기화 함으로써 재사용될 수 있는 문제를 잡아 주셨는데요.

init을 동적으로 호출하지 않아도 될 것 같다는 생각이 들어요!
생성자로 cars를 받아보는 방법은 어떨까요?

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/util/NumberGenerator.kt
> +class NumberGenerator : RandomNumberGenerator {
인터페이스와 구현체 이름이 서로 바뀐 것 같지 않나요!?

외부에서는 인터페이스 타입으로 사용하는데 RandomNumber라는 이름을 알 필요가 있을까요?

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +    }
> 위 말씀이 조금 이해가 안되어서 질문 드립니다!ㅠ
움직이기 위한 조건을 사전에 계산을 하는 로직을 미리 수행하는 것으로 이해를 했는데, car.move() 이전에 조건 계산을 수행하게 하는 것인지 궁금합니다!

제가 드린 질문은 "**미리 계산할 필요가 있는가**" 에 대해서입니다.

```
자동차들을 움직인다 -> 자동차가 움직인다 
-> 움직이기 위한 조건을 확인한다 -> 조건에 따라 움직인다.
```

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/model/RacingGame.kt
> +        }
-

전체적으로 map 함수를 같이 수정 해 주세요! 검색을 통해 많은 레퍼런스를 확인할 수 있습니다.

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/util/RandomNumberGenerator.kt
> +package racing.util
공통으로 사용될 수 있는 개념을 보통 util 패키지에 모아두고는 하는데요.
하지만, 유틸을 "먼저" 만드는 것은 객체지향 설계에 방해요소가 될 수 있습니다.

실제 도메인 로직에 필요한 개념을 유틸로 만들다보면, 무분별한 재사용 코드가 될 수 있고
객체에 대한 응집도를 해칠 수 있습니다.

2023-02-12 01:46 UTC, laco-dev commented on src/main/kotlin/racing/validators/CarNameValidator.kt
> +object CarNameValidator {
Validator같은 클래스도 도메인 모델에서는 일반적으로 잘 만들지 않아요.

1. 객체의 역할로 볼 수 있을까?
2. 자동차가 가져야 하는 책임으로 봐야 하지 않을까?
3. 재사용의 목적이라면 모델을 만들어야 하지는 않을까?

이 개념도 다음 미션에서 학습할 내용이기 때문에 참고만 해 주시면 됩니다.
이런 상황에서는 Validator를 만드는 것이 아닌 CarName이라는 모델을 만들어서 해결하고는 합니다.

```kotlin
class CarName(val value: String) {
   init {
      require(자동차 이름은 5글자 이하)
      require(자동차 이름은 빈값일 수 없음)
   }
}

class Car(carName: CarName) { ... }
```

2023-02-12 01:47 UTC, merged

2023-02-12 16:30 UTC, rhkrwngud445 commented on src/main/kotlin/racing/controller/RacingCarController.kt
> +            cars.add(Car(it))
리턴값이 필요 없으므로 forEach로 수정하는 것이 좋겠네요! 다른 부분도 함께 수정하겠습니다!