[수달] 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #48
Opened 2023-02-09 07:21 UTC by otter66

한가지 어려웠던 점이 있다면, 값에 대한 검증을 어느 곳에서 하는 것이 좋을지 잘 모르겠습니다. 
(모델에서 객체가 생성될 때 객체에 대한 검증을 하는 것이 좋을지, 입력 후 곧바로 검증을 하는 것이 좋을지 등이 고민됩니다. 
조언을 주신다면 감사하겠습니다!)

부족한 첫 페어 프로그래밍이지만, 바쁘신 와중에도 세심하게 코드를 읽고 리뷰해주시는 소중하신 분께 감사드립니다!!

2023-02-09 13:21 UTC, BeokBeok requested changes
자동차 경주 구현 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-02-09 13:21 UTC, BeokBeok commented on src/main/kotlin/racingcar/controller/RacingController.kt
> +    private val racingService: RacingService = RacingService(),
생성자로 의존성 주입 👍

2023-02-09 13:21 UTC, BeokBeok commented on src/main/kotlin/racingcar/service/RacingService.kt
> +    }
본 미션에서 자동차가 전진 가능 여부에 대한 로직은 핵심 로직입니다.
isMove 함수에 대한 테스트 코드를 작성해보면 어떨까요?

2023-02-09 13:21 UTC, BeokBeok commented on src/main/kotlin/racingcar/utils/BlankRemover.kt
> +    private fun removeBlank(text: String): String = text.trim()
공백을 제거하는 함수를 잘 구현해주셨네요. 👍 
하지만 대체로 커스터마이징한 함수보다는 시스템함수가 더 가독성이 좋습니다.
불필요한 함수를 인라인화해보면 어떨까요? (이하 관련 내용 동일)

2023-02-09 13:21 UTC, BeokBeok commented on src/main/kotlin/racingcar/utils/BlankRemover.kt
> +    }
removeBlank함수를 호출하게 되면, 인자로 전달된 값(원본)을 변경하게 됩니다.
원본을 변경하게 되면, 원본 데이터를 참조하고 있는 곳에서 예상치 못한 오류가 발생할 수 있습니다.
원본을 변경하지 않도록 코드를 개선해보면 어떨까요?

2023-02-09 13:21 UTC, BeokBeok commented on src/main/kotlin/racingcar/utils/Strings.kt
> +const val WINNER_NOTIFICATION_MESSAGE = "최종 우승자"
주석을 활용하여 각 상수값이 의미하는 바를 잘 나타내주셨네요. 👍 
주석을 활용해도 좋지만, object를 활용하여 관련 상수들끼리 묶어보면 어떨까요?

2023-02-09 13:21 UTC, BeokBeok commented on src/test/kotlin/racingcar/ApplicationKtTest.kt
> +    fun `전체 기능 노말 테스트`(carNames: String, roundCount: String) {
"전체 기능"이란 어떤 것을 의미할까요? (이하 관련 내용 동일)

2023-02-09 13:21 UTC, BeokBeok commented on src/test/kotlin/racingcar/service/RacingServiceTest.kt
> +    fun `자동차 객체 생성 노말 테스트`(carName: String) {
"노말 테스트"는 어떤 것을 의미할까요? (이하 관련 내용 동일)

2023-02-09 13:21 UTC, BeokBeok commented on src/test/kotlin/racingcar/ApplicationKtTest.kt
> +                // Arguments.of("otter", "${Int.MAX_VALUE}"),
```suggestion
```
불필요한 주석은 제거해보면 어떨까요?

2023-02-09 13:23 UTC, BeokBeok commented
> 한가지 어려웠던 점이 있다면, 값에 대한 검증을 어느 곳에서 하는 것이 좋을지 잘 모르겠습니다.
(모델에서 객체가 생성될 때 객체에 대한 검증을 하는 것이 좋을지, 입력 후 곧바로 검증을 하는 것이 좋을지 등이 고민됩니다.
조언을 주신다면 감사하겠습니다!)

A. 값에 따라 다르겠지만, 생성자 검증은 객체 생성 시에 검증을 해주는 것이 좋습니다. 😄

2023-02-10 01:25 UTC, otter66 commented on src/main/kotlin/racingcar/service/RacingService.kt
> +    }
이 부분에 대해서 테스트를 하는 것이 좋다고 생각했지만, 외부에서 사용되지 않아 private인 함수이기에 테스트를 해야할지 고민을 했습니다. 역시 바로 캐치 당해버렸네요🥲...! 
고민을 할 때 잠시 찾아보았을 때에는 "비공개 메서드의 모든 코드를 비공개 메서드에 독립적인 방법으로 테스트 하라."와 비슷한 내용들의 글들을 볼 수 있던 것 같습니다. 
따라서 isMove함수를 사용하는 moveRandomly함수를 테스트하였습니다.
private 함수를 테스트하는 좋은 방법을 찾지 못하였는데, 혹시 좋은 방법이 있을까요?

2023-02-10 01:42 UTC, otter66 commented on src/main/kotlin/racingcar/utils/BlankRemover.kt
> +    }
기능을 분리하는 것에 집중하다보니 조금씩 산으로 가게된 것 같네요...
말씀해주신 것처럼 데이터가 바뀔 때에는 원본 데이터를 참조하는 곳에서 변형을 하는 것이 좋은 것 같습니다!
곧바로 반영하겠습니다! 감사합니다!

2023-02-10 01:42 UTC, otter66 commented on src/main/kotlin/racingcar/utils/BlankRemover.kt
> +    private fun removeBlank(text: String): String = text.trim()
이 부분도 시스템함수를 곧바로 사용하는 것이 좋을 것 같습니다!
말씀해주셔서 감사합니다!

2023-02-10 04:43 UTC, otter66 commented on src/test/kotlin/racingcar/ApplicationKtTest.kt
> +    fun `전체 기능 노말 테스트`(carNames: String, roundCount: String) {
전체 기능이란 모듈들을 통합한 Controller의 테스트였는데, 
"전체 기능 테스트"라는 말에서 어떤 것들을 테스트하는 것인지 명시하기 어려운 이름인 것 같네요. 
말씀 주셔서 감사합니다!

2023-02-10 14:39 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-02-10 14:39 UTC, BeokBeok commented on src/main/kotlin/racingcar/service/RacingService.kt
> +    }
isMove 함수가 테스트하기 어려운 이유는, 랜덤값을 함수 내부에서 생성하고 있기 때문입니다.
만약 값을 함수의 파라미터로 받게되면 어떨까요?
추가로 private 함수의 테스트 코드는 방법이 아예 없는 것은 아니오나, 대체적으로 작성할 수 없습니다.
private 함수를 테스트하기 위해서는, 외부에서도 접근이 가능하도록 public하게 만드는 것입니다.
내부에서만 접근하는데 public으로 만드는 것이 이상하게 느껴지신다면, 해당 로직을 클래스로 분리하면 됩니다. 😅

2023-02-10 14:39 UTC, BeokBeok commented on src/main/kotlin/racingcar/controller/ViewController.kt
> +    }
상수를 companion object로 잘 구현을 해주셨습니다. 👍 
Controller는 View와 Domain에 접근이 가능하므로, 자칫 잘못하면 Controller가 커지게 됩니다.
상수값도 Input과 관련된 값이 있고 Output과 관련된 값이 있습니다.
Input과 관련된 상수값은 InputView에서, Output과 관련된 상수값은 OutputView에서 관리해보면 어떨까요?

2023-02-10 14:39 UTC, BeokBeok commented on src/test/kotlin/racingcar/service/RacingServiceTest.kt
> +    fun `최종 우승자 산출 정상 테스트`(cars: List<Car>, expectedWinnersCount: Int) {
"정상 테스트"는 어떤 것을 의미할까요? (이하 관련 내용 동일)

2023-02-10 14:39 UTC, BeokBeok commented on src/test/kotlin/racingcar/service/RacingServiceTest.kt
> +    fun `최종 우승자 산출 예외 테스트`(cars: List<Car>, expectedWinnersCount: Int) {
어떤 경우에 예외가 발생할까요? (이하 관련 내용 동일)

2023-02-10 14:40 UTC, merged

2023-02-11 00:46 UTC, otter66 commented on src/main/kotlin/racingcar/service/RacingService.kt
> +    }
늦은 시간임에도 빠르게 리뷰 남겨주셔서 정말 감사드립니다!
말씀해주신 것처럼 내부에서 생성하는 것이 아닌 파라미터로 받는 방법르로 수정한다면 테스트가 수월할 것 같습니다. 리펙터링에 바로 적용시키도록 하겠습니다! 감사합니다!!

2023-02-11 01:22 UTC, otter66 commented on src/main/kotlin/racingcar/controller/ViewController.kt
> +    }
말씀해주신 것처럼 하나에서 모두 관리하는 것보다 각각으로 나누어 관리하는 것이 좋을 것 같습니다!
조언 주셔서 감사합니다! 다음 리펙터링에 적용시켜보겠습니다!!

2023-02-11 01:53 UTC, otter66 commented on src/test/kotlin/racingcar/service/RacingServiceTest.kt
> +    fun `최종 우승자 산출 예외 테스트`(cars: List<Car>, expectedWinnersCount: Int) {
테스트 상황을 더 자세하게 나타낼 수 있는 방법을 찾아보겠습니다!!!
리뷰 감사드립니다!!!