[링링] 2단계 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #58
Opened 2023-02-12 06:18 UTC by RightHennessy

레아 안녕하세요 ~! 
주말은 잘 보내고 계신가요? 1단계 리뷰 해주신 것을 바탕으로 코드를 수정해보았습니다. 😊

2023-02-12 06:25 UTC, RightHennessy commented on src/main/kotlin/racingcar/misc/Util.kt
> +            break
리뷰해주신 Util의 기준이 무엇인지에 대해 고민해보고, tryAndRerun 함수는 남겨두고 generateRandom 함수는 다른 파일로 이동해주었습니다.

Util의 특징은 일단 프로젝트 전역에서 사용되고 특정 로직이나 독립적인 기능을 하는 것을 모아두는 것이라고 생각했습니다. 리뷰 이후 생각해보니 랜덤함수를 생성하는 함수는 특정 클래스 (CarManager)에서만 사용되어 Util 클래스 밖에 존재하는 것이 맞는 판단이라고 생각하여 변경했습니다.

2023-02-12 08:33 UTC, RightHennessy commented on src/main/kotlin/racingcar/controller/World.kt
>              initAttemptCount()
앞에서 lateinit을 쓰지 않고 구현을 하니 입력의 오류가 발생했을 시 다시 입력 받는 부분이 애매해져서 일단은 tryAndRerun 함수를 삭제하고 try-catch문으로 대체했습니다. 레아가 말씀하신 runCatching은 내일 시간이 된다면 적용해보도록 하겠습니다. ㅎㅎ🤣

2023-02-12 08:42 UTC, RightHennessy commented on src/main/kotlin/racingcar/view/OutputView.kt
> +
문자열을 만드는 부분이 도메인 로직에 의존하지 않도록 OutputView에서 생성하도록 수정했습니다.
이렇게 수정하는게 맞는지 확신이 들지는 않네요 😥

2023-02-12 13:18 UTC, woowahan-leah requested changes
안녕하세요 링링!

Step2 구현을 잘 해주셨습니다 💯  이전 단계 리뷰도 잘 반영해주셨네요.
고민해보시면 좋을만한 코멘트를 달았으니 확인해주시면 감사하겠습니다.

자동차 경주 리뷰 기간이 얼마 남지 않았지만 "랜덤한 로직을 어떻게 테스트할지"에 대해 고민하며 이번 단계를 마무리하신다면 더욱 의미있는 시간이 될거예요.

다음 리뷰 요청에는 머지하도록 할게요 ☺️
궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/Application.kt
> +    } catch (e: IllegalArgumentException) {
에러 catch문 구체화 👍

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/controller/World.kt
> +            OutputView.printLnMessage(OutputView.MSG_INPUT_CAR_NAME)
컨트롤러에서 OutputView에 `MSG_INPUT_CAR_NAME`라는 상수가 존재한다는 것을 알 필요가 있을까요~? 외부에서 객체의 구체적인 구현을 참조하기보다 메세지만 던져보는 구조로 개선해보세요 🙂 
```kotlin
OutputView.자동차 이름을 받을 때 사용할 안내메세지를 출력해줘()
```

다른 코드에서도 객체 내부의 구체적인 구현을 참조하는 곳이 있나요? 메세지를 던지는 구조로 바꾸면 어떤 점이 좋을까요?

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/entity/Car.kt
> +data class Car(val name: Name, var position: Position = Position(0)) {
외부에서 Car 객체에 접근하여 position값을 수정하게 되어 의도치 않은 버그를 마주할 수 있습니다. 어떻게 개선해볼 수 있을까요?

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/entity/Car.kt
> +    override fun toString() = name.toString()
https://github.com/woowacourse/kotlin-racingcar/pull/51#discussion_r1102190035 이 코멘트에 대해 고민해보세요 🙂

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/entity/Name.kt
>      }
유의미한 상수-클래스 연결 👍

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/model/CarManager.kt
>      }
init 블럭에서 초기화할 때를 제외하고 cars가 Mutable한 List 타입이 될 필요가 있을까요? List 타입으로도 충분히 구현 가능해보입니다.

힌트: 이런 상황에서 강의에서 배운 부생성자를 활용해보세요!

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/model/CarManager.kt
>      }
이전 리뷰: https://github.com/woowacourse/kotlin-racingcar/pull/51#discussion_r1102197588
NumberGenerator를 인터페이스로 만들었지만 여전히 attempt()에 대한 테스트는 안되고 있습니다. 함수 내에서 RandomNumber object라는 구체적인 값을 참조하기 때문인데요, 강의에서도 설명되었듯이 이러한 "테스트하기 어려운 영역"을 분리하는 것에 집중해볼까요?

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/misc/Util.kt
> +            break
링링의 많은 고민이 느껴집니다! Util 클래스, Util 함수에 대해 객체지향 관점에서 어떤 시각이 있는지 찾아보면 더욱 재밌으실거예요. 🙂 

https://stackoverflow.com/questions/3340032/are-utility-classes-evil

2023-02-12 13:18 UTC, woowahan-leah commented on src/main/kotlin/racingcar/view/OutputView.kt
> +
1. 도메인 로직에 의존하고 있는 부분이 남아있는 것으로 보이네요!(override된 toString())
2. `it.position.toInt()` -> 뷰에서 도메인 로직을 너무 잘 알고 있다는 생각이 들 수 있을 것 같아요. 위의 코멘트에서처럼 메세지를 던지는 구조로 만들어보는건 어떨까요?

2023-02-13 01:21 UTC, RightHennessy commented on src/main/kotlin/racingcar/controller/World.kt
> +            OutputView.printLnMessage(OutputView.MSG_INPUT_CAR_NAME)
안그래도 같은 함수를 재활용하는 것이 나은가 아니면 상황 별로 분리하여 함수를 만드는 것이 나을까에 대해 페어와 얘기했었습니다. 만약 메시지만 던져보는 구조를 사용한다면

1. OuputView에 어떤 메시지를 사용해야하는지, World를 사용하는 입장에서는 알 필요가 없다.
2. print를 하기위해 어떤 함수를 써야할지 찾을 노력이 필요가 없다.
3. 만약 printLnMessage 함수에 변경이 생긴다면 이 함수를 사용하는 여러 함수를 바꿔야하기 때문에 이러한 불편함이 사라진다.

정도로 생각해봤는데 제 생각이 맞을까요? 😂

2023-02-13 02:07 UTC, RightHennessy commented on src/main/kotlin/racingcar/model/CarManager.kt
>      }
init 문을 제거하고 map을 사용하여 Car 객체로 Name들을 변경해주는 방식으로 하였습니다.!

2023-02-13 03:03 UTC, RightHennessy commented on src/main/kotlin/racingcar/entity/Car.kt
> +    override fun toString() = name.toString()
toString override를 삭제하고 OutputView에서 name 을 string으로 변경하는 방법으로 바꾸었습니다!

2023-02-13 03:05 UTC, RightHennessy commented on src/main/kotlin/racingcar/view/OutputView.kt
> +
다음과 같이 변경했는데,, 확신이 들지 않는 이유는 무엇일까요 😥

1. override toString 삭제 후 OutputView에서 직접 문자열로 바꾸는 방식으로 변경했습니다.
2. 포지션만 찍어주는 함수인 makePositionLog를 만들었습니다.

2023-02-13 03:26 UTC, RightHennessy commented on src/main/kotlin/racingcar/entity/Car.kt
> +    override fun toString() = name.toString()
Name class에서 override toString으로 name 값만 문자열로 만들어주고, 나머지 출력문 생성은 OutputView에서 하도록 했습니다. 계속 고민해봤는데.. 해결방법이 떠오르지 않네요 😥

2023-02-13 03:27 UTC, RightHennessy commented on src/main/kotlin/racingcar/entity/Car.kt
> +data class Car(val name: Name, var position: Position = Position(0)) {
이 부분의 원래 코드로 되돌려 놓았습니다. position을 private으로 선언하여 외부에서는 접근하지 못하도록 하고, getPosition을 통해 값을 받아올수만 있게 했습니다.

2023-02-13 04:50 UTC, woowahan-leah commented on src/main/kotlin/racingcar/controller/World.kt
> +            OutputView.printLnMessage(OutputView.MSG_INPUT_CAR_NAME)
페어와 같이 더 합리적인 답을 찾기 위해 노력하는 모습 보기 좋습니다 👍  

링링이 답변해주신 것 모두 맞다고 생각해요. 추가로 변경사항의 전파에 대해 좀 더 이야기해보자면, 출력 요구사항이나 출력 방법이 바뀌더라도 해당 변경사항이 호출부까지 전파되지 않는다는 것이 가장 중요한 장점이라고 생각해요. 호출부에서 구체적인 요구사항에 의존하게 되면 해당 요구사항을 변경할 때 변경점이 늘어나게 됩니다.

앞으로도 객체 지향 관점에 대해 고민하며 미션을 진행하실 텐데요, OOP의 가장 중요한 본질 중 하나는 프로그램이 커졌을 때 유지 보수와 변경사항의 전파를 막기 위함에 있다는 것을 기억하며 메세지를 던져보세요 🙂

2023-02-13 08:51 UTC, RightHennessy commented on src/main/kotlin/racingcar/model/CarManager.kt
>      }
6시까지 제출인데 아직 분리하는 것에 대해 잘 이해하지 못한 것 같습니다. .ㅜㅜ 
이후에 계속 해보도록 하겠습니다..😥

2023-02-14 01:52 UTC, woowahan-leah approved these changes
안녕하세요 링링! 
리뷰 반영을 잘 해주셨습니다 💯 

조금 고민해보시면 좋을 내용을 코멘트로 달았으나 이번 미션은 여기서 마무리하도록 하겠습니다.
다음 미션을 진행하기 전에 다음 글이 도움이 되면 좋겠습니다.
- https://velog.io/@eddy_song/alan-kay-OOP

자동차 경주 미션 진행하느라 고생 많으셨습니다~
다음 미션도 화이팅입니다 🙏

2023-02-14 01:52 UTC, woowahan-leah commented on src/main/kotlin/racingcar/entity/Car.kt
> +data class Car(val name: Name) {
data class 활용 👍

2023-02-14 01:52 UTC, woowahan-leah commented on src/main/kotlin/racingcar/model/CarManager.kt
> +    private val cars = names.map { Car(it) }
불필요한 mutable 타입 제거 👍

2023-02-14 01:52 UTC, woowahan-leah commented on src/main/kotlin/racingcar/model/CarManager.kt
>      }
> 다음과 같이 변경했는데,, 확신이 들지 않는 이유는 무엇일까요 😥
> 1. override toString 삭제 후 OutputView에서 직접 문자열로 바꾸는 방식으로 변경했습니다.
> 2. 포지션만 찍어주는 함수인 makePositionLog를 만들었습니다.

확신이 들지 않는 이유는 model에서 View를 참조하고 있기 때문입니다. 🤔 
model에서 직접적으로 View의 함수를 호출하기보다 model의 결과물을 View에 넘겨주는 방향으로 구현한다면 이러한 참조를 끊을 수 있습니다.
다음 미션에서는 View에서 모델을 알지만 모델에서는 View를 알지 못하는 구조를 만드는걸 고민해보세요.

2023-02-14 01:52 UTC, woowahan-leah commented on src/test/kotlin/racingcar/model/RandomNumberTest.kt
> +}
> NumberGenerator interface 함수를 만들어 main에서는 RandomNumber로 랜덤함수를 생성하고, test시에는 직접만든 list를 numberGenerator로 넘겨주어 테스트하게 했습니다.!!

테스트 가능한 구조로 변경 👍 
고민해볼만한 요소: RandomNumber object는 싱글톤일 필요가 있을까요?

2023-02-14 01:52 UTC, woowahan-leah commented on src/test/kotlin/racingcar/model/CarManagerTest.kt
> +    }
단위 테스트를 할 때 given when then 패턴에 대해 알아보고 적용하면 정형화된 단위 테스트 패턴을 만들 수 있습니다. 이 코멘트는 참고만 해주세요!

2023-02-14 01:52 UTC, merged