[우기] 2단계 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #59
Opened 2023-02-12 07:39 UTC by boogi-woogi

제임스의 피드백 내용 바탕으로 수정하였습니다!

* 입력을 검증하는 InputValidator의 유틸리티성을 없애기 위해서 두가지 UseCase로 나눈뒤 Controller에 주입했습니다.
* CarRacingGame을 Test하기 위해서 두가지 클래스로 분리가 되었었는데 제임스가 말씀해주신대로 두 가지 이상의 기능을 수행하고 있는 것으로 보여서 우승자만을 판단하는 클래스를 새로 생성하였습니다.
* 단지 상수 하나로 인해서 다른 클래스에 의존하고 있는 상황을 만들지 않기 위해서 해당 상수를 최대한 필요로 하는 곳에 private 멤버로 선언하였습니다.

domain/game 패키지를 테스트하기 위해서 코드를 작성하다보니 우승자를 판단하는 클래를 테스트하기 위한 RefereeTest와 CarTest에 공통적으로 필요한 부분이 보여서 공통적인 부분을 상속으로 코드의 재사용을 줄여보았는데 이런 상황일때 상속을 쓰는 것이 적절한 것인지 잘 모르겠습니다!🤔

2023-02-12 17:39 UTC, woowajames requested changes
피드백 반영 너무 수고하셨습니다. 💯 
처음보다 코드가 많이 깔끔해진 것 같아요! 👍 몇 가지 추가 사항과 질문하신 내용에 대해 코멘트 남겼으니 확인 부탁드려요. 조금만 더 힘내시죠! 아자!!

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
>          }.onFailure { exception ->
처음에 try catch를 사용 하셨을 때 다른 부분에 더 집중 하시길 바라는 마음에 해당 부분은 피드백을 일부러 하지 않았었는데 고쳐 주셨네요! 굿굿 👍 !! 연산자 사용을 지양하면 더욱 좋을 것 같습니다.

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
> +        val names = validateUseCases.validateSuccessiveTokenizer(InputView.inputCarNames())
굳이 다른 클래스를 통해서 호출될 필요가 있을까요?

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/domain/validator/ValidateUseCases.kt
> +)
이러한 형태의 data class가 어떤 장점이 있을까요? class가 아닌 data class를 사용하면서 어떠한 효과를 얻고자 하셨는지 궁금합니다. 불필요한 클래스가 아닌가 싶기도 하네요.

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/domain/generator/CarGenerator.kt
> +            (MINIMUM_NUMBER..MAXIMUM_NUMBER).random()
첫 피드백 후 바로 반영이 안되어서 아쉬웠던 부분인데 잘해주셨습니다! 테스트가 한결 편해지셨을 것으로 기대합니다! 😄

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/domain/validator/ValidateNumberOfTry.kt
> +class ValidateNumberOfTry {
validator에 있는 클래스들의 이름은 좀 더 명사에 가깝게 변경하는게 좋을 것 같습니다.

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/model/Car.kt
> +package model
별도로 모델을 분리해주셨네요. Car 클래스는 왜 도메인이 아닌 모델로 구분 하셨을까요? 정답이 정해진 게 아니라 모호하게 느껴질 수도 있지만 이 기회에 도메인, 모델, 도메인 모델이란 키워드를 공부해보는 것도 좋을 것 같습니다.

2023-02-12 17:39 UTC, woowajames commented on src/test/kotlin/domainTest/gameTest/RefereeTest.kt
> +class RefereeTest : GameBaseTest() {
테스트 하고자 하는 클래스명Test(CarRacingGameRefereeTest)가 일반적인 형태입니다. 여전히 어느 클래스를 위한 테스트인지 바로 인지 하기에는 불편한 느낌이에요. 그리고 Referee도 좋지만 개인적으로는 이전의 Winner라는 단어가 좀 더 어떤 역할인지 잘 와닿는 것 같아요.

2023-02-12 17:39 UTC, woowajames commented on src/test/kotlin/domainTest/gameTest/GameBaseTest.kt
> +}
이렇게 공통 부분을 상속 받아서 쓰는 형태에 대해 질문 주셨는데요. 테스트 코드로 리팩터링이 필요한 부분이고 재사용성이 높아지면 좋다고 생각합니다. 다만 테스트 케이스의 유연성을 해치지 않는 선에서요. 여기서 굳이 하나의 꼬인 생각을 해보자면 CarTest에서 전진 테스트를 할 때 5라는 값일 때도 정상적으로 동작하는지 확인하려면 현 상황에서 쉽게 변경이 가능한가요?

2023-02-12 17:39 UTC, woowajames commented on src/main/kotlin/view/OutputView.kt
>              println(CAR_PATH.format(car.name, DASH.repeat(car.position)))
이 방법 너무 좋네요! 🥇

2023-02-13 08:14 UTC, boogi-woogi commented on src/main/kotlin/controller/CarRacingGameController.kt
> +        val names = validateUseCases.validateSuccessiveTokenizer(InputView.inputCarNames())
만약 검증하는 부분의 로직 역시 컨트롤러로 들어가게 된다면 컨트롤러의 역할이 너무 거대해지는 것과 동시에 테스트가 어려워 질것이라는 생각으로 나누게 되었습니다. 혹시 제임스는 어떠한 이유로 입력을 검증하는 클래스가 따로 나뉠 필요가 없다고 생각하셨는지 궁금합니다!

2023-02-13 08:56 UTC, boogi-woogi commented
* Validator 클래스들에 있던 로직들을 컨트롤러로 이동 시켰는데 제임스가 의도한 것이 이것인지 잘 모르겠습니다!  그런데 해당 validate하는 함수들이 private 으로 선언되어 있으면 테스트에서 해당 validate함수들을 테스트 할 수가 없어서 접근 제한자를 public으로 바꾸었는데 이것을 private으로 하면서 테스트 코드 작성에는 문제가 없는지에 대한 고민을 해보았지만 아직까지는 해답이 떠오르지 않았습니다ㅜㅜ
* 그리고 Car를 model로 분류했던 이유는 자신의 상태(position)가 변경될때마다 Controller로 그것을 알리고 있는것이 model의 역할과 비슷하다고 생각하여 model로 분류했었습니다. 제임스의 말대로 도메인 모델, 모델, 도메인 키워드에 대해서 더욱 학습해보겠습니다.

위의 내용 이외에도 제임스가 리뷰해주신 내용에 대해서 마지막까지 모두 완료하지 못했지만 앞으로 미션을 진행하면서 계속해서 배워나가겠습니다! 제 첫 리뷰를 맡아주셔서 정말 감사합니다!!!

2023-02-13 10:22 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
> +        val names = validateUseCases.validateSuccessiveTokenizer(InputView.inputCarNames())
컨트롤러가 비대해지는 것은 좋지 않은게 맞습니다. 컨트롤러로 옮기라는 의미가 아니고 validateNumberOfTry와 validateSuccessiveTokenizer는 다른 역할을 하는 객체인데 왜 굳이 ValidateUseCases라는 데이터 클래스로 묶었는지 질문드린겁니다. 그냥 개별 클래스로 둬도 상관없다고 생각합니다.

2023-02-13 10:25 UTC, boogi-woogi commented on src/main/kotlin/controller/CarRacingGameController.kt
> +        val names = validateUseCases.validateSuccessiveTokenizer(InputView.inputCarNames())
두 클래스 모두 검증하는 역할을 하는 것이 관련이 있다고 생각해서 묶었는데 앞으로는 data class의 의미에 대해서 다시 생각해보고 바로 수정하겠습니다!

2023-02-13 10:35 UTC, woowajames commented
>

2023-02-13 10:42 UTC, woowajames requested changes
우기! 2단계 구현도 고생하셨습니다! 👍
마지막으로 기존에 잘되었던 부분이 커뮤니케이션 오류로 변경된 것이 너무 아쉬워서 코멘트 남겼습니다.
해당 부분만 빠르게 한 번 복구해보시죠! 질문 하신 내용은 DM으로 더 논의해보면 좋겠습니다! 🥇

2023-02-13 10:42 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
> +    }
컨트롤러로 옮기라는 의미가 아니었습니다. 이전처럼 별도의 클래스로 두는게 좋겠습니다.

2023-02-13 10:42 UTC, woowajames commented on src/main/kotlin/controller/CarRacingGameController.kt
> +    }
컨트롤러로 옮기라는 의미가 아니었습니다. 이전처럼 별도의 클래스로 두는게 좋겠습니다.

2023-02-13 10:42 UTC, woowajames commented on src/main/kotlin/domain/game/CarRacingGameWinner.kt
> +class CarRacingGameWinner {
Winner로 꼭 바꾸라는 뜻은 아니었고 개인적인 선호였습니다. 만약 이렇게 바꾸실거면 CarRacingGame의 프로퍼티명 등 관련있는 부분도 적절히 변경되면 좋겠습니다.

2023-02-13 10:42 UTC, woowajames commented on src/test/kotlin/domainTest/CarRacingGameControllerTest.kt
> +class CarRacingGameControllerTest {
컨트롤러를 굳이 domainTest라는 패키지에 둘 필요는 없다고 생각해요.

2023-02-13 10:42 UTC, woowajames commented on src/test/kotlin/domainTest/GameBaseTest.kt
> +open class GameBaseTest {
테스트를 위한 클래스일 뿐 실제로 어떤 테스트를 하는 클래스는 아니라서 네이밍만 보면 혼란스러울 것 같습니다.

2023-02-13 17:30 UTC, woowajames approved these changes
우기! merge 하겠습니다! 🙌 첫 번째 미션 정말 고생 많으셨습니다. 💯
피드백 반영도 열심히 해주시고 추가적인 고민거리에 대해서도 함께 이야기 나눌 수 있어서 너무 좋은 시간이었습니다. 앞으로의 미션도 잘하실거라 믿습니다. 화이팅! 💪

2023-02-13 17:31 UTC, merged