[핑구] 2단계 자동차 경주 제출합니다.
woowacourse/kotlin-racingcar pull request #62
Opened 2023-02-12 09:56 UTC by pingu244

안녕하세요! 지난번에 주신 피드백을 바탕으로 하여 수정해보았습니다.
더하여 두가지 질문이 있습니다!

1. 피드백 주신 대로 SAM인 numberGenerator 인터페이스를 람다로 선언해보려 노력했습니다. 관련 개념은 처음이라 구글링을 통해 알아보았는데 예시로 나오는 setOnClickListener처럼 SAM 인터페이스를 인자로 받는 함수를 하나 만들었습니다. 그 후
setNumber{ return STOP_NUMBER }
이런식으로 사용해보려 했는데 되지않아 의문입니다.. 어떤식으로 하면 제대로 구현할 수 있을지 조언 부탁드립니다..!

2. CarRacingGame 클래스의 startDriving 함수는 random값으로 인해 테스트하기 힘든 부분이니 Car객체의 move함수를 테스트하는 것만으로도 충분할지 궁금합니다. 

친절하고 자세한 피드백 항상 감사드립니다!

2023-02-13 04:19 UTC, malibinYun requested changes
2단계 미션 고생 많으셨어요!!
이전 피드백을 열심히 반영하려는 모습이 엿보였습니다 :)

질문은 아래 코멘트에 달아둘게요!
피드백 반영하시고 다시 리뷰 요청 부탁드려요~

2023-02-13 04:19 UTC, malibinYun commented on src/main/kotlin/domain/CarRacingGame.kt
> +            path.add(car.move(racingNumberGenerator.generate()))
이 부분도 코틀린 확장함수를 활용해보는 것은 어떨까요?

2023-02-13 04:19 UTC, malibinYun commented on src/main/kotlin/domain/Initialize.kt
> +) {
Initialize란 이름은 어떤 일을 하는 지 다른 개발자들이 봤을 때 한 번에 이해되는 이름일까요?
또, 클래스명은 명사형으로 작성하는 것이 일반적입니다 :)

2023-02-13 04:19 UTC, malibinYun commented on src/main/kotlin/model/Car.kt
> +            CAR_NAME_BLANK_ERROR_MSG
https://github.com/woowacourse/kotlin-racingcar/pull/38#discussion_r1102735596 이 리뷰를 참고해서 반영해보아요 🙂

2023-02-13 04:19 UTC, malibinYun commented on src/main/kotlin/model/PathState.kt
>      MOVE("-"),
PathState는 도메인을 표현하는데, View에 해당하는 값을 가지고 있네요!
View를 그리는 것은 View에서만 수행해보는 건 어떨까요?

2023-02-13 04:19 UTC, malibinYun commented on src/test/kotlin/domain/InitializationTest.kt
> +        }
테스트에 필요한 값을 로직을 통해 준비하기 보다 하드코딩으로 준비해보는 것은 어떨까요?
또, 테스트는 반복문으로 검증하기보다, 한 줄로 검증해보는 것은 어떨까요?

2023-02-13 04:19 UTC, malibinYun commented on src/test/kotlin/domain/RefereeTest.kt
> +    }
테스트 값을 잘 준비해주셨네요! 👍
다만, 검증문이 너무 길어질 수도 있기에, when/then을 나눠보는 것은 어떨까요?

2023-02-13 04:19 UTC, malibinYun commented on src/test/kotlin/model/CarTest.kt
> +    }
검증문은 하드코딩으로 구성해보는 것은 어떨까요?
관련 좋은 글을 하나 공유드립니다 :) https://jojoldu.tistory.com/615

또, assertEquals 보다는, assertJ를 적극 활용해주세요!

2023-02-13 04:19 UTC, malibinYun commented on src/test/kotlin/model/CarTest.kt
> +        })
랜덤에 대한 테스트를 아주 잘 구현해주셨네요! 👍

2023-02-13 04:23 UTC, malibinYun commented
> 피드백 주신 대로 SAM인 numberGenerator 인터페이스를 람다로 선언해보려 노력했습니다. 관련 개념은 처음이라 구글링을 통해 알아보았는데 예시로 나오는 setOnClickListener처럼 SAM 인터페이스를 인자로 받는 함수를 하나 만들었습니다. 그 후
setNumber{ return STOP_NUMBER }
이런식으로 사용해보려 했는데 되지않아 의문입니다.. 어떤식으로 하면 제대로 구현할 수 있을지 조언 부탁드립니다..!

Kotlin은 interface와 람다를 엄격하게 구분짓는데요, 이때문에 불편함을 겪는 사람이 많았나 봅니다. 지금 현상 처럼요!
그래서 코틀린 1.4 업데이트로 fun interface라는 키워드를 제공해주었어요.
interface내 메서드가 한 개면 람다로 바로 쓸 수 있는 기능이에요 :)

> CarRacingGame 클래스의 startDriving 함수는 random값으로 인해 테스트하기 힘든 부분이니 Car객체의 move함수를 테스트하는 것만으로도 충분할지 궁금합니다.

Car의 move와는 또 다른 로직들이 RacingGame에 있으므로 더 구현해주어야 해요 :)
Car의 랜덤의 요소는 이미 numberGenerator를 통해서 제어할 수 있으니 충분히 테스트를 작성할 수 있어요!
View를 제외한 다른 모든 클래스에 대해서 테스트 코드를 작성해주세요 🙂

2023-02-13 14:48 UTC, malibinYun requested changes
2단계 미션 피드백 반영하시느라 고생 많으셨어요!
점점 코드가 깔끔하게 변하고 있네요 👍
마지막으로 한 번 더 미션을 다듬어보아요 😊

피드백 반영하시고 다시 리뷰 요청 부탁드릴게요!
궁금한 게 있으시면 질문 남겨주셔도 좋아요 :)

2023-02-13 14:48 UTC, malibinYun commented on src/main/kotlin/controller/RacingCarController.kt
> +        OutputView.printMsg(RESULT)
carPath의 size가 결국 numberOfTry이니, numberOfTry은 필요 없어보여요 :)

2023-02-13 14:48 UTC, malibinYun commented on src/main/kotlin/domain/CarRacingGame.kt
> +        return this
1회의 CarPath를 만드는 메서드를 만들고,
n번 위의 메서드를 호출해 list로 만들어보세요 :)

위 방법을 잘 조합하면 kotlin의 확장 함수로 아주 짧게 코드를 작성해볼 수 있습니다 :)
코틀린스러운 코드에 도전해보세요! 💪

2023-02-13 14:48 UTC, malibinYun commented on src/main/kotlin/domain/InputRefinement.kt
> +) {
이 객체는 각기 다른 일들을 맡고있어 보여요.
입력 값 가공기인데, Car를 반환하는 것은 다소 어색해보입니다.

자동차를 만들어내는 역할은 이미 분리되어있어서, 돌고 돌아 함수를 실행시키는 느낌이 많이 드네요! 🙂

시도 횟수 Integer는 InputView에서 가져오는 값으로도 충분해 보여요 :)

2023-02-13 14:48 UTC, malibinYun commented on src/main/kotlin/view/OutputView.kt
> +    }
kotlin의 when식을 이용하면 이렇게도 작성할 수 있답니다 😊
```suggestion
    private fun PathState.changeToMark(): String = when (this) {
        PathState.MOVE -> MOVE_MARK
        PathState.STOP -> STOP_MARK
    }
```

2023-02-13 14:48 UTC, malibinYun commented on src/main/kotlin/view/OutputView.kt
> +            pathMarks += pathState.changeToMark()
이런 코틀린 확장함수도 있어요!
```kotlin
"1".repeat(5)   // == "11111"
```

2023-02-13 14:48 UTC, malibinYun commented on src/test/kotlin/domain/CarRacingGameTest.kt
> +    })
이 전략은 테스트에 인라인 람다로 작성하는 게 더 가독성에 좋습니다 :)

2023-02-13 14:48 UTC, malibinYun commented on src/test/kotlin/domain/CarRacingGameTest.kt
> +    }
테스트에서는 매직 리터럴들을 상수로 분리할 필요가 없다고 생각해요.
오히려 어떤 값이 들어가는 지 아래에서 보고 와야하기에 가독성을 해질 수 있다고 생각해요 🙂

2023-02-13 14:48 UTC, malibinYun commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
generateCars()의 반환 값은 List\<Car> 이니, Car에 대한 리스트를 하드코딩으로 만들어서 직접 비교해보는 것은 어떨까요?

2023-02-14 09:46 UTC, pingu244 commented on src/main/kotlin/domain/CarRacingGame.kt
> +        return this
CarPath를 만드는 메서드가 recordPath고 그걸 startDriving에서 map으로 반복하여 호출하고 있습니다. 어떻게하면 더 코틀린스럽게 할 수 있을까요?

2023-02-14 09:46 UTC, pingu244 commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
generateCars()의 반환값과 제가 만든 리스트가 같다고 판단하지않습니다.. 
expected: [model.Car@269f4bad, model.Car@5ed731d0]
 but was: [model.Car@62435e70, model.Car@339bf286]
오류 내용을 보니 
둘이 다른 저장공간에 있어서 그런것같은데 이런 경우에는 어떻게 테스트하는 것이 좋을까요?

2023-02-14 09:50 UTC, pingu244 commented on src/test/kotlin/domain/CarRacingGameTest.kt
> +    })
인라인 람다로 작성하면 가독성에 좋다는 것이 잘 와닿지 않습니다..! 인라인 함수를 찾아보니 람다식을 사용했을 때 무의미한 객체 생성을 예방하기 위한 함수라고 하는데
이를 사용했을 때 왜 가독성이 좋아지나요?

2023-02-14 09:51 UTC, pingu244 commented on src/test/kotlin/domain/CarRacingGameTest.kt
> +    })
> 이 전략은 테스트에 인라인 람다로 작성하는 게 더 가독성에 좋습니다 :)



> 이 전략은 테스트에 인라인 람다로 작성하는 게 더 가독성에 좋습니다 :)

인라인 람다로 작성하면 가독성에 좋다는 것이 잘 와닿지 않습니다..! 인라인 함수를 찾아보니 람다식을 사용했을 때 무의미한 객체 생성을 예방하기 위한 함수라고 하는데
이를 사용했을 때 왜 가독성이 좋아지나요?

2023-02-14 09:51 UTC, pingu244 commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
> generateCars()의 반환 값은 List<Car> 이니, Car에 대한 리스트를 하드코딩으로 만들어서 직접 비교해보는 것은 어떨까요?

generateCars()의 반환값과 제가 만든 리스트가 같다고 판단하지않습니다..
expected: [model.Car@269f4bad, model.Car@5ed731d0]
but was: [model.Car@62435e70, model.Car@339bf286]
오류 내용을 보니
둘이 다른 저장공간에 있어서 그런것같은데 이런 경우에는 어떻게 테스트하는 것이 좋을까요?

2023-02-14 13:56 UTC, malibinYun commented on src/test/kotlin/domain/CarRacingGameTest.kt
> +    })
네~ 람다를 활용하게 되면 object, override fun 등등... 에 대한 키워드를 사용해서 익명클래스를 만들 필요 없이
단순한 람다 한 줄로 원하는 NumberGenerator를 만들어줄 수 있기 때문이에요 :)
fun interface와 SAM에 대해 학습해보시길 권장드려요 😊

2023-02-14 13:58 UTC, malibinYun commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
네~! Car의 내용물은 같은데 Car끼리는 서로 다르다고 나타나고 있군요!

왜 이런 현상이 발생할까요?
`Car("1") == Car("1")`  를 실행할 때, ==는 어떤 값을 비교하고 있을까요?

2023-02-15 16:01 UTC, pingu244 commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
> 네~! Car의 내용물은 같은데 Car끼리는 서로 다르다고 나타나고 있군요!
> 
> 왜 이런 현상이 발생할까요? `Car("1") == Car("1")` 를 실행할 때, ==는 어떤 값을 비교하고 있을까요?

답변주신대로 찾아보니 둘의 주소값을 비교하여 오류가 발생한다는 것을 알았습니다. 둘의 주소값이 아닌 내용물을 비교하기위해 Car클래스 내에 equals와 hashCode를 오버라이딩을 했습니다.
제가 생각하기에 이 코드들은 Test만을 위한 코드라 불필요하다고 생각됩니다. 이런식으로 객체끼리 비교를 위하여 도메인 클래스 내에 테스트만을 위한 오버라이딩이 필요한 경우, 도메인 클래스를 건드리지 않는 선에서 테스트를 진행할 수 있는 방법이 있을까요?

2023-02-16 13:45 UTC, malibinYun commented on src/test/kotlin/model/generator/CarGeneratorTest.kt
> +    }
저는 이름이 같고 동일 거리에 있는 자동차라면 동일 자동차라고 생각해요 :)
그래서 equals & hashcode의 오버라이드는 비단 테스트 만을 위한 코드라고 생각하진 않아요 😀
해당 메서드들을 직접 오버라이드 하는 것이 마음에 걸리신다면, data class에 대해서도 학습해보셔도 좋겠어요 🙂

2023-02-16 13:47 UTC, malibinYun approved these changes
많은 피드백 반영 하시느라 고생 많으셨어요!!
저와 이야기했던 내용들이 앞으로 코드 작성하실 때 도움이 되셨으면 좋겠네요 :)
다른 미션들도 잘 완주하시길 응원할게요!
고생 많으셨습니다 😊

2023-02-16 13:47 UTC, merged