[크롱] 2단계 자동차 경주 미션 제출합니다!
woowacourse/kotlin-racingcar pull request #65
Opened 2023-02-12 15:43 UTC by krrong

달아주신 코멘트 잘 확인했습니다! 😊
피드백을 반영한 이번 PR의 수정 내용은 다음과 같습니다!
- 외부로 공개하지 않는 변수 cars 초기화 방법 수정
- GameController에서 UI에 대한 의존성 분리

2023-02-12 16:20 UTC, galcyurio requested changes
이미 MVC로 잘 구현되어 있어서 수정할 부분이 많지 않네요 👍 
마지막으로 한 가지만 더 개선해보고 끝내면 좋겠어요.
피드백 확인 부탁드립니다 🙂

2023-02-12 16:20 UTC, galcyurio commented on src/test/kotlin/racingcar/controller/GameControllerTest.kt
> +    }
Controller 테스트 케이스 작성 👍 

이 방법을 떠올리는게 쉽지 않았을텐데 잘 작성해주셨네요 👏 👏 

조금 아쉬운 점은 assert문이 테스트 본문에 존재하는게 아니라 다른 영역에 존재한다는 점입니다.
이 점은 고차함수를 넘기는 방식을 통해 개선할 수 있습니다.
마지막으로 이 부분만 수정해보면 좋겠어요.

2023-02-13 08:42 UTC, krrong commented on src/test/kotlin/racingcar/controller/GameControllerTest.kt
> +    }
고차함수를 활용하여 test코드 내에 assert문을 작성해보았습니다! 고차함수를 적용하는게 어려워서 맞게 작성한 것인지 잘 모르겠네요.. 더 열심히 공부해봐야 할 것 같아요ㅎㅎ 감사합니다!

2023-02-13 13:12 UTC, galcyurio approved these changes
지금까지 자동차 미션 고생하셨습니다 :)
다음 로또 미션도 힘내세요!

2023-02-13 13:12 UTC, galcyurio commented on src/test/kotlin/racingcar/controller/GameControllerTest.kt
> +    }
잘 작성해주셨습니다. :+1: 

조금 더 쉽게 생각하면 굳이 assert문을 함수로 만드는 대신 접근할 수 없는 데이터를 바깥으로 전달하기만 하셔도 됩니다.

```kotlin
class TestOutputViewInterface(
    val onPrintWinner: (List<String>) -> Unit,
) {
    override fun printWinner(names: List<String>) {
        onPrintWinner(names)
    }
}
```
```kotlin
@Test
fun `runGame 함수를 통한 최종 우승자 정상 출력 확인`() {
    // given
    var actual: List<String> = emptyList()
    val gameController =
        GameController(
            RaceManager(TestNumberGenerator(mutableListOf(1, 2, 4))),
            TestInputViewInterface(),
            TestOutputViewInterface { actual = it }
        )

    // when
    gameController.runGame()

    // then
    assertThat(actual).containsExactly("test3")
}
```

2023-02-13 13:12 UTC, merged