Step2
woowacourse/kotlin-racingcar pull request #73
Opened 2023-02-13 03:23 UTC by chws0508

안녕하세요! 
오늘 오후부터 우테코 행사가 있어서,  이번이 마지막 리뷰 요청일 수 있을 것 같아서 마지막으로 공부하면서 느낀 몇가지 궁금한 점 남깁니다.

1. 앞서서 Sealed class 대신 kotlin.Result를 활용하여 불필요한 코드양을 줄일 수 있다고 하셨는데, kotlin.Result 를 활용하여 실패 케이스를 출력하기 위해서는 exception을 던지고, runcatching 을 이용하여 onFailure에서 exception 메세지를 받아서 출력해야 하는데, 이러면 제가 앞서 말했던 "자동차의 이름은 5글자를 넘어서면 안된다" 에 대해서 exception을 발생시킬 수 밖에 없는건가요? exception으로 던지기 싫지만 실패 케이스를 출력하고 싶을때는 어떻게 처리해야 할까요?

2. Domain 에서 OutputView 에게 넘겨주는 형태를 String 말고 객체를 넘겨주어 그 객체를 OutputView에서 처리하라고 리뷰 해주셨었는데,  실제 코드에서는 List<String> 형태로 넘겨주어 OutputView에서 처리하였는데, List<Car> 형태로 넘겨주고 Car에서 변수를 뽑아서 써도 될까요? 이렇게 하면 View와 도메인의 의존성이 높아지게 되서 안좋은 걸까요?

3. 제가 InputView에서 ValidationResult를 도메인으로 넘겨주었는데, View에서 Domain으로 넘겨주는 형식은 자유로운 걸까요??

4. 제가 컨트롤러 run 테스트를 진행해 보았는데, OutPutView내부 함수에서 assert를 활용하였는데, 이 방법 외에는 다른 방법이 없을까요?? 

끝으로 지금까지 저의 코드를 봐주시고 리뷰해주셔서 정말 감사합니다! 이 리뷰들을 통해 많은 깨달음을 얻은 것 같습니다!

2023-02-13 08:21 UTC, chws0508 commented on src/main/kotlin/view/InputView.kt
InputView에서 에러를 검사하고, 출력하도록 코드를 수정하였는데, 이런 에러 처리는 View영역에서 하면 역할에 대한 책임 범위를 벗어나는 걸까요? 아니면 InputView단에서하는 에러처리와 Domain에서 하는 에러처리의 기준이 있을까요?

2023-02-13 12:34 UTC, galcyurio requested changes
2단계 리팩터링 고생하셨습니다.
Controller 단위 테스트까지 잘 해주셨네요 👍 
질문해주신 부분과 피드백을 코멘트로 남겨두었으니 확인해주세요.

2023-02-13 12:34 UTC, galcyurio commented on src/main/kotlin/view/InputView.kt
UI의 역할은 아닌 것 같은데 그렇다고 domain 이라고 보기 힘든 것들에 대한 비즈니스 로직들은 Controller에 두시면 좋습니다.
지금처럼 validation을 해본 뒤에 실패했다면 다시 View에게 재입력을 받게 하기도 쉬운 layer이며 View와는 다르게 단위 테스트도 가능하기 때문입니다.

2023-02-13 12:34 UTC, galcyurio commented on src/main/kotlin/controller/RacingGameController.kt
>  import model.Name
> 앞서서 Sealed class 대신 kotlin.Result를 활용하여 불필요한 코드양을 줄일 수 있다고 하셨는데, kotlin.Result 를 활용하여 실패 케이스를 출력하기 위해서는 exception을 던지고, runcatching 을 이용하여 onFailure에서 exception 메세지를 받아서 출력해야 하는데, 이러면 제가 앞서 말했던 "자동차의 이름은 5글자를 넘어서면 안된다" 에 대해서 exception을 발생시킬 수 밖에 없는건가요? exception으로 던지기 싫지만 실패 케이스를 출력하고 싶을때는 어떻게 처리해야 할까요?

Result.Failure를 만들기 위해서는 Exception을 생성하기만 하고 던지지는 않으셔도 됩니다.

```kotlin
fun checkName(name: String): Result<String> {
    return if (name.isEmpty()) {
        Result.failure(IllegalStateException())
    } else {
        Result.success(name)
    }
}
```

Exception을 만드는 것도 code smell로 여겨진다면 [Either](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/)와 같은 클래스를 사용하거나 범용적으로 쓸 수 있는 Result 클래스를 직접 만드셔도 좋습니다 :)

2023-02-13 12:34 UTC, galcyurio commented on src/test/kotlin/controller/RacingGameControllerTest.kt
> +        }
> 제가 컨트롤러 run 테스트를 진행해 보았는데, OutPutView내부 함수에서 assert를 활용하였는데, 이 방법 외에는 다른 방법이 없을까요??

코틀린에서는 매개변수로 고차함수를 넘길 수 있습니다.
TestOutputView의 생성자로 고차함수를 넘겨서 시도해보세요 :)

2023-02-13 12:34 UTC, galcyurio commented on src/main/kotlin/controller/RacingGameController.kt
>      }
> Domain 에서 OutputView 에게 넘겨주는 형태를 String 말고 객체를 넘겨주어 그 객체를 OutputView에서 처리하라고 리뷰 해주셨었는데, 실제 코드에서는 List 형태로 넘겨주어 OutputView에서 처리하였는데, List 형태로 넘겨주고 Car에서 변수를 뽑아서 써도 될까요? 이렇게 하면 View와 model의 의존성이 높아지게 되서 안좋은 걸까요?

이전에는 domain 객체에서 아래와 같이 UI의 역할이 RacingCarGameService에 포함되어 있었기 때문에 드렸던 피드백입니다.
지금은 잘 수정되었습니다 🙂 

```kotlin
fun getWinnersOutput(carsInfo: List<Car>): String {
    var winners = "최종 우승자: "

    carsInfo.forEach { car ->
        winners += "${car.name}, "
    }
    return winners.substring(0, winners.length - 2)
}
```

2023-02-14 15:33 UTC, galcyurio approved these changes
자동차 경주 마지막까지 고생하셨습니다 👏 👏 
다음 미션도 힘내세요!

2023-02-14 15:33 UTC, merged