[자동차 경주 구현] 벼리 미션 제출
woowacourse/kotlin-racingcar pull request #93
Opened 2024-02-15 05:53 UTC by gaeun5744

코드리뷰하면서 요청드릴 부분이 있습니다.

Car 클래스의 forwardCount를 getForwardCount()를 통해서 값을 가져오도록 구현했는데, 이 방법이 코틀린 체계에 맞는 방법인지 궁금하여 질문드립니다.

2024-02-15 12:40 UTC, malibinYun requested changes
1단계 미션 고생 많으셨어요 :)
생각해볼만한 곳에 코멘트 남겨두었어요.
깊게 고민해보고 스스로의 답을 찾아보셨으면 좋겠어요 :)
피드백 반영 후 다시 리뷰 요청 부탁드러요!

2024-02-15 12:40 UTC, malibinYun commented on docs/README.md
> +     - 이때, 1명 이상일 수 있다.
기능 목록을 잘 정리해주셨네요 👍

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/Application.kt
새로 생성된 파일 모두 마지막 라인의 줄바꿈이 없네요!
마지막 라인에 줄바꿈을 추가해주는 건 어떨까요?

줄바꿈을 추가해야하는 이유는 무엇일까요 ?_?

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/model/Car.kt
> +    }
> Car 클래스의 forwardCount를 getForwardCount()를 통해서 값을 가져오도록 구현했는데, 이 방법이 코틀린 체계에 맞는 방법일까요?

틀린 방법은 없다고 생각해요. 다양한 방법이 존재해요 :)
작성하신 코드도 수많은 방법 중 하나예요.
다만, Kotlin 공식문서에서 안내하는 방법들이 있지요! 이것을 컨벤션이라고 부릅니다.
아래 프로퍼티에 대해 공식 문서에 자세히 안내하고 있으니, 이 기회에 잘 알아보는 시간을 가져보세요 :)
https://kotlinlang.org/docs/classes.html#constructors
https://kotlinlang.org/docs/properties.html

그렇다면, 특정 팀에서는 코틀린 공식 가이드로 작성하지 않고, 그 팀만의 다른 방식대로 코드를 작성한다면 그것은 틀린방법일까요?
어떻게 생각하시나요? 🙂

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/model/CarsManager.kt
> +    }
CarsManager 객체를 다른 사람들이 활용해야하는 상황이 왔을때, CarsManager 객체 생성 후 반드시 create를 불러야만 한다는 사실을 바로 알 수 있을까요?
만약 바로 move()를 호출한다면 어떻게 될까요?
문제가 생긴다면, 어떻게 해결해볼 수 있을까요?

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/model/RandomNumber.kt
> +    }
랜덤 요소를 테스트 가능하도록 만들어주셨네요 👍

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/util/NumberGenerator.kt
> +
> 저희는 util 패키지를 '단독으로 사용 가능하며, 다른 패키지에서 활용될 수 있다'라고 정의하였기 때문에 NumberGenerator 인터페이스를 util 패키지에 넣었습니다. 혹시 이러한 방식으로 분리하는게 맞을까요?

맞고 틀림이 없음은 여기에서도 여전히 적용되어요 :)

파운데이션, 하이라이터, 컨실러 등등.. 이것들이 담긴 상자에 "도구 상자" 라는 이름을 적어두어도, 사실 올바른 표현이지요!
피부화장을 위한 "도구"니까요!

하지만, 과연 피부화장을 위한 도구를 찾아야할 때, "도구 상자" 라는 이름이 붙은 상자에 원하는 화장품들이 존재할 거란 생각이 한 번에 들 수 있을까요?

혼자서는 가능할지도 모르겠어요. 스스로가 만들었고, 스스로가 관리하니까요.
하지만 친구가 우리 집에서 내 컨실러를 잠깐 빌리고 싶을 때, 스스로 한 번에 찾을 수 있을까요?

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/util/Validation.kt
> +object Validation {
Validation 객체로 검증에 대한 역할을 한꺼번에 묶은 이유가 궁금해요! 🙂

2024-02-15 12:40 UTC, malibinYun commented on src/main/kotlin/view/OutputView.kt
> +        private fun getRoundResult(car: Car) = "${car.name} : ${"-".repeat(car.getForwardCount())}"
이 함수들은 클래스 멤버가 아닌, companion object에 위치 시킨 이유가 무엇인지 궁금해요!

2024-02-15 12:40 UTC, malibinYun commented on src/test/kotlin/model/CarTest.kt
> +    fun `전진 기능 테스트`() {
다른 사람이 봤을 떄, 함수 몸체를 보지 않고 테스트명만 보고 이 테스트가 무엇을 검증하고자 하는 지 한 번에 유추해낼 수  있을까요?

2024-02-15 12:40 UTC, malibinYun commented on src/test/kotlin/model/CarsManagerTest.kt
> +    @MethodSource("provideRandomNumberExample")
`@CsvSource`를 활용해보는 건 어떨까요?

2024-02-16 00:27 UTC, gaeun5744 commented on src/main/kotlin/Application.kt
덕분에 POSIX에 대해 배웠습니다 감사합니다!! 😆

2024-02-16 07:57 UTC, gaeun5744 commented on src/main/kotlin/util/Validation.kt
> +object Validation {
1. 검증 메서드는 UI 로직이 아니기 때문에 InputView에 그대로 두기 부적합하다고 생각했습니다.
2. 검증 로직은 InputView를 위한 `helper`의 역할이 강하다 생각했습니다.

위의 두가지 이유로 util 함수로 빼두었습니다!
물론 InputView 안에 nested class로 둘까 라는 생각이 들었지만, 그럼 한 파일에 과도하게 로직이 들어있어 가독성이 떨어질 것 같아 따로 분리했습니다!

혹시 InputView 안에 넣는게 더 적합하다고 생각하시나요??  리뷰어님의 생각이 궁금합니다!!!

2024-02-17 09:01 UTC, gaeun5744 commented on src/main/kotlin/model/CarsManager.kt
> +    }
아 지적 감사합니다!! init 블록 안에 넣을 생각을 못했네요

2024-02-17 09:04 UTC, gaeun5744 commented on src/main/kotlin/view/OutputView.kt
> +        private fun getRoundResult(car: Car) = "${car.name} : ${"-".repeat(car.getForwardCount())}"
사실 문자열은 전부 companion object에 넣었기 때문에, 통일성을 위해 문자열 생성 메서드 또한 그곳에 넣었습니다. 그래야 가독성이 좋아질거라 생각했습니다!!

2024-02-17 09:11 UTC, gaeun5744 commented on src/main/kotlin/model/Car.kt
> +    }
리뷰 감사합니다!! 보내주신 문서 덕분에 properties 컨벤션에 대해 더 공부할수 있었습니다
문서를 읽으며 제 코드가 `주생성자에서 프로퍼티를 초기화` 하는 것에 너무 얽매여 있다는 생각이 들었습니다. 그래서 kotlin에서 제공하는 getter를 활용하는 대신 get 함수를 따로 만든것 같네요.....

또한 말씀해주신 컨벤션에 대해 더 고민해봤지만 정말 어려운 문제 같습니다. 어떻게 보면 kotlin이 한국어와 같다는 생각이 드는 질문이었어요
의사소통을 위해서는 당연히 표준 맞춤법을 지켜야 하지만, 너무 얽매여 있지 않기 때문에 계속 새로운 단어들이 등장하고 언어가 발전하고 있지 않나라는 생각이 들었어요

어떻게 보면 다양하게 활용하기 때문에 kotlin이라는 언어가 발전할 수 있지 않나 싶었습니다. 다만 해당 부분은 기본적인 맞춤법과 같은 영역이라는 생각이 들어 수정하겠습니다!! 조언 감사합니다!!

2024-02-17 11:32 UTC, gaeun5744 commented
안녕하세요 리뷰어님!! 코드를 리팩토링 하다가 궁금한 점이 생겨서 질문 드립니다.
현재 저희는 테스트를 위해 `interface`를 따로 만들어서 랜덤 숫자에 대한 테스트가 가능하도록 구현했습니다.
그러나 이 방법은 그저 `테스트`만을 위해 새로운 코드를 작성하는 것이라 여겨서 옳지 않은 방법이라는 생각이 문듯 들었습니다.
혹시 랜덤 숫자를 테스트 할 수 있는 다른 방법을 추천해 주실 수 있나요??

2024-02-17 12:04 UTC, gaeun5744 commented on src/main/kotlin/view/OutputView.kt
> +        private fun getRoundResult(car: Car) = "${car.name} : ${"-".repeat(car.getForwardCount())}"
해당 질문을 보고, 메서드의 정의에 대해 다시 고민해봤습니다.

저는 객체지향의 사실과 오해를 보면서 메서드란, `객체의 상태를 변화시키고 다른 객체와 상호작용 하기 위한 수단`이라 이해했습니다.

그런데 문듯 생각해보니 OutputView는 상태를 저장하지도 않고, 다른 객체와 상호작용하고 있지 않다고 느꼈습니다... 그래서 지금은 OutputView를 유틸리티 클래스로 만들기 위해 object로 바꿨습니다!!

2024-02-18 03:28 UTC, malibinYun commented on src/main/kotlin/model/Car.kt
> +    }
그래서 코드를 구성하는 형태를 "언어" 라고 부르나봐요.
언어에서도 사라지는 단어들, 새로 생기는 단어들, 잘 변하지 않는 것들 등등... 이런 것들이 있으니까요. 참 어려운 세계예요.

인터넷 게임 용어들이 즐비한 커뮤니티에서 사용하는 말들을 일상생활에서 사용하면 아무도 못알아듣지만, 게임 속에서는 모두가 알아듣지요.
그렇기에 최대한 "언어"는 일상 생활에서 사용할 수 있도록 누구나 알아들을 수 있는 말을 사용해야한다 생각해요.
그렇게 저는 가독성이 챙겨질 수 있다고 믿고 있어요.

코틀린 문법을 엄청나게 활용해서 이렇게까지 된다고?? 할 정도의 무언가를 내놓더라도, 읽는 데 한세월이고 알아보기 어렵다면 저는 "투머치코틀린" 이라고 생각해요 🙂

2024-02-18 03:36 UTC, malibinYun commented on src/main/kotlin/util/Validation.kt
> +object Validation {
> 다만, 이렇게 로직을 구현하는 사람이 많지 않아서 망설여지는데 혹시 이 방법이 괜찮을것 같나요????

한국에서 살아가기 참 어려운 요소예요, 그렇죠?
이걸 따라가는 게 이게 꼭 나쁘지만은 않기도 해요. 모두가 익숙한 것을 나도 한다면, 다른 곳에 가서도 익숙한 것일테니까요.

그런데 지금 만큼은! 이런 생각에 경계를 가지셔도 좋겠어요.
그만큼, 더 낫다고 생각하게 된 스스로의 이유를 단단히 다져보세요. 그리고 설득력있게 다듬어보세요.
만약 논리적으로 생각하다가, 스스로가 "엥?? 전혀 논리적이지 않은걸??" 라는 걸 발견하게 될지도 모르겠어요. 그러면 의견을 다시 되돌아보면 되는 것이니까요.

---
<details>
<summary> 개인적인 제 의견 </summary>

역할에 맞는 검증까지만 수행하는 것을 선호해요.

입력 값에 대한 검증이라면 입력 값에 대한 검증만.
도메인의 검증이라면 도메인에는 해당의 검증만.

역할에 따라 적절히 분리하는 것을 선호해요 🙂
</details>

2024-02-18 03:50 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요!
다음 미션을 위해 머지하겠습니다.
남겨둔 코멘트를 많이 고민해보시고, 피드백은 다음 미션에 반영해주세요!
다음 미션도 화이팅입니다 :)

2024-02-18 03:50 UTC, malibinYun commented on src/main/kotlin/controller/RacingController.kt
> +) {
생성자에 아무 것도 없으니 소괄호는 지워주세요!

2024-02-18 03:50 UTC, malibinYun commented on src/main/kotlin/model/Car.kt
> +        private set
getter는 공개하고, setter는 감추고.
kotlin property 문법을 잘 활용해주셨네요! 👍

다만, 프로퍼티는 생성자 위에 위치시켜야 해요 :)
https://kotlinlang.org/docs/coding-conventions.html#interface-implementation-layout

2024-02-18 03:50 UTC, malibinYun commented on src/main/kotlin/model/CarsManager.kt
> +class CarsManager(carsName: List<String>, private val randomNumber: NumberGenerator) {
CarsManager 보다 좀 더 현실세계를 모방한 단어로 변경해보는 건 어떨까요?

2024-02-18 03:50 UTC, malibinYun commented on src/main/kotlin/model/CarsManager.kt
> +        private set
cars를 val로 변경하면 어떻게 될까요?
```suggestion
    val cars: List<Car>
        private set
```

2024-02-18 03:50 UTC, malibinYun commented on src/test/kotlin/model/CarTest.kt
> +    }
`@ParameterizedTest`를 활용해보는 건 어떨까요?

2024-02-18 03:50 UTC, malibinYun commented on src/test/kotlin/model/CarsManagerTest.kt
> +        }
자동차를 생성할 때 외부에서 초기 거리 값을 넘길 수 있게 객체를 구성해서, 원하는 초기 거리 값을 가질 수 있도록 만들어보는 건 어떨까요?

2024-02-18 03:54 UTC, merged

2024-02-18 03:54 UTC, malibinYun commented
> 안녕하세요 리뷰어님!! 코드를 리팩토링 하다가 궁금한 점이 생겨서 질문 드립니다.
현재 저희는 테스트를 위해 interface를 따로 만들어서 랜덤 숫자에 대한 테스트가 가능하도록 구현했습니다.
그러나 이 방법은 그저 테스트만을 위해 새로운 코드를 작성하는 것이라 여겨서 옳지 않은 방법이라는 생각이 문듯 들었습니다.
혹시 랜덤 숫자를 테스트 할 수 있는 다른 방법을 추천해 주실 수 있나요??

지금은 테스트에서만 사용하니 충분히 그렇게 느낄 수 있을거라 생각해요.
하지만 지금 갑자기 요구사항으로, 4이상일 때만 움직이는 것을 포함해서, 다른 종류의 조건을 가진 전략도 여러개가 추가된다면 어떻게될까요?
interface로 구현했던 프로젝트와 그렇지 않은 프로젝트는, 이 요구사항 반영을 위해 어떤 변경점들이 생겨날까요?

2024-02-18 15:36 UTC, gaeun5744 commented on src/test/kotlin/model/CarsManagerTest.kt
> +        }
그 부분에 대해서 고민해봤습니다..! 
다만 Car의 초기 거리값을 넣을 수 있도록 하더라도, CarsManager 내부에서 create 함수를 호출하기 때문에 외부에서 따로 초기값을 설정하기 힘들어 보입니다ㅠㅠ 하지만 확장성에 좋아 보여서 초기값 설정을 따로 추가했습니다!!