[자동차 경주 구현] 서기 미션 제출합니다.
woowacourse/kotlin-racingcar pull request #96
Opened 2024-02-15 06:20 UTC by Namyunsuk

잘 부탁 드립니다!

2024-02-15 11:02 UTC, Gyuil-Hwnag requested changes
안녕하세요 서기! 
이번 미션을 함께하게 된 두루라고 합니다. 잘부탁드려요!

자동자 경주 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on docs/README.md
> +## 요구사항
README 작성 좋습니다👍

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/controller/RacingController.kt
> +        outputView.printWinners(carsManager.getWinners())
해당 내용의 경우 하나의 함수는 하나의 기능만을 담당한다는 생각으로 아래처럼 각각의 기능을 담당하는 함수별로 분류 해봐도 좋을 것 같습니다!!
예시) initialize(초기화), play(게임), result(결과)

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/Car.kt
> +    }
companion object를 활용한 상수 관리 좋습니다💯

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/Car.kt
> +    }
개인적인 생각이지만 Car라는 class에 fowarCount 값을 파라미터로 가지면서 변경하는 방법도 좋지만 Car 클래스 내부적으로 forwardCount를 가지고 있는 것도 고민해볼 필요는 있는 것 같습니다!

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/CarsManager.kt
> +    private fun isMove(): Boolean = randomNumber.generate() >= FORWARD_STANDARD_NUMBER
각각 기능별로 함수 구현 너무 잘해주셨네요💯

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/RandomNumber.kt
> +    }
인터페이스를 활용한 랜덤숫자생성 클래스 정말 좋은 것 같습니다💯

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/main/kotlin/util/Validation.kt
> +    }
Validation에 대한 내용을 분리하여 별도의 object로 만들어서 관리하는 것 정말 좋은 것 같습니다💯

참고로 함수 네이밍의 경우 Validation(확인) 이라는 뜻에 맞게 carName -> checkName으로 변경 고려해 해보는 것도 좋을 것 같습니다!!
import 하였을 때 단순히 carName 만으로는 어떤 기능을 담당하는 함수인지에 대한 판별이 어려울 수도 있겠다는 생각이 들어 참고차 코멘트 남겨두었습니다🥲

추가적으로 논의해보면 좋을것 같아서 남겨두었습니다~
Car 클래스 에서 체크하지 않고 ValidationUtils로 따로 뽑으신 이유가 있을까요??

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/test/kotlin/model/CarTest.kt
> +    }
테스트 코드 깔끔하게 잘 작성해주셨네요!!
너무 잘해주셨지만 테스트 코드 전반적으로 참고할 만한 내용이 있어서 코멘트 남겼습니다~
테스트 코드의 경우 어떤 테스트인지 확실하게 알 수 있게 네이밍을 정해주는 것도 좋은 것 같습니다
~~~kotlin
    @Test
    fun `자동차가 1칸 이동하면 거리는 1이다`() {
        // given
        val car = Car("서기")
        // when
        isMoveExample.forEach { car.moveForward(it) }
        // result 
        assertThat(car.getForwardCount()).isEqualTo(2)
    }
~~~

2024-02-15 11:02 UTC, Gyuil-Hwnag commented on src/test/kotlin/model/CarsManagerTest.kt
> +    }
해당 내용도 위의 CarTest 와 동일하게 수정해보셔도 좋을 것 같습니다!!

2024-02-15 11:09 UTC, Gyuil-Hwnag commented
> 안녕하세요 리뷰어님 미션을 진행하면서 궁금한 점이 생겨서 질문 드립니다. Car클래스에서 forwardCount를 getForwardCount()함수를 통해서 값을 가져오도록 구현하였는데 이 방식이 적절한 방법인지 그리고Validtion과 NumberGenerator 인터페이스가 서비스와 직접적인 관련이 없다 생각이 들어 util 패키지에 위치하였습니다. 이 것 또한 맞는 것인지 의문이 들어 질문드립니다.
> 
> 잘 부탁 드립니다!

안녕하세요 서기~ 
추가적으로 질문주신거 답변 남겨두었습니다!!
개인적인 생각으로는 코드에 항상 정답은 없다고 생각이 들긴 합니다. 각각 규모와 상황에 맞는 구조와 코드가 존재한다는 생각이 들긴 합니다~
Validation, NumberGenerator로 분리한 내용은 오히려 기능이 추가되면 될수록 더 빛을 볼 수 있는 분리라고 생각이 드는 내용이었습니다!!

2024-02-16 08:54 UTC, Namyunsuk commented on src/main/kotlin/model/Car.kt
> +    }
forwardCount는 조건에 관계없이 항상 0을 기본 값으로 가져야 하기에  forwardCount를 주 생성자가 아닌 클래스 내부에 선언함으로써 Car인스턴스 생성 시 forwardCount의 초깃 값에 대해 접근 할 수 없도록 하였습니다.
또한 getForwardCount메서드를 삭제하고 프로퍼티의 특성을 활용하여 값을 가져오도록 수정하였습니다.

2024-02-16 08:54 UTC, Namyunsuk commented on src/main/kotlin/util/Validation.kt
> +    }
사용자가 유효하지 않은 값을 입력 할 시 Car까지 가지 않고 inputView선에서 예외처리가 되도록 하였습니다. 또한 유효하지 않은 값을 입력했을 시 다시 입력하는 기능을 추가하는 등 기능을 확장 할 시 더 유용할 것 같아 다음과 같이 하였습니다.

2024-02-16 11:40 UTC, Gyuil-Hwnag commented on src/main/kotlin/util/Validation.kt
> +    }
타당한 이유 정말 좋습니다ㅎㅎ😆

2024-02-16 11:52 UTC, Gyuil-Hwnag approved these changes
서기 해당 미션 너무 고생 많으셨습니다! 
리뷰 반영 정말 잘 해주셨네요.

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션에서 반영해주셔도 좋을 것 같습니다.

추가로 미션 제출전에 다음 설정으로 문법에 안 맞는 내용은 없는지 확인해 보시는 것도 좋을것 같습니다~😆
gradlew clean ktlintCheck 

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/CarsManager.kt
> +    }
외부에서의 Setter접근을 막기위한 방어적 연산자 정말 좋습니다👍
거기다가 초기화 까지 너무 깔끔하게 잘해주셨네요💯

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/model/CarsManager.kt
> +}
다음 설정 옵션을 활성화하여 EOF 경고를 없애주세요🥲
File > Preferences > Editor > General > Ensure every saved file ends with a line break

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/util/Validation.kt
> +    }
함수명들이 이전보다 좀 더 명확해진 느낌이네요👍

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/util/Validation.kt
> +}
다음 설정 옵션을 활성화하여 EOF 경고를 없애주세요🥲
File > Preferences > Editor > General > Ensure every saved file ends with a line break

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/util/Validation.kt
> +        require(carsName.contains(CAR_NAME_SPLITTER)) { SPLITTER_ERROR_MESSAGE }
이전에도 봤었지만 require을 활용한 것 정말 좋네요💯

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/controller/RacingController.kt
> +    }
함수 분리 정말 깔끔하네요💯💯💯

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/view/InputView.kt
> +}
다음 설정 옵션을 활성화하여 EOF 경고를 없애주세요🥲
File > Preferences > Editor > General > Ensure every saved file ends with a line break

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/main/kotlin/view/OutputView.kt
> +}
다음 설정 옵션을 활성화하여 EOF 경고를 없애주세요🥲
File > Preferences > Editor > General > Ensure every saved file ends with a line break

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/test/kotlin/model/CarTest.kt
> +    }
테스트 코드명 한눈에 보고 어떤 내용인지 파악이 정말 잘되네요💯💯💯

2024-02-16 11:52 UTC, Gyuil-Hwnag commented on src/test/kotlin/model/CarTest.kt
> +    }
해당 내용의 경우 테스트 코드가 많아질 경우에 재사용 가능하게 하려는 것이 목적이라면 네이밍도 그에 맞게 "2칸이동"등으로 수정해보는 것도 고민해봐도 좋을 것 같습니다!!💪

2024-02-16 11:53 UTC, merged

2024-02-17 07:16 UTC, Namyunsuk commented on src/main/kotlin/util/Validation.kt
> +}
설정방법까지 알려주셔서 감사합니다 😭 
수정하겠습니다!

2024-02-17 07:17 UTC, Namyunsuk commented on src/test/kotlin/model/CarTest.kt
> +    }
테스트코드를 작성함에 있어서 함수의 네이밍만 생각해왔었는데 테스트 함수에 사용되는 값들에 대해서는 의식한 경우가 없는 데 리뷰어님 말씀 보고 많은 생각을 해볼 수 있었습니다 🙇‍♂️