[자동차 경주 구현] 차람 미션 제출합니다.
woowacourse/kotlin-racingcar pull request #97
Opened 2024-02-15 06:26 UTC by aprilgom

안녕하세요 리뷰어님, 저는 6기 안드로이드 크루 차람이라고 합니다.
페어(오둥이)와 미션을 진행하던 중, 몇 가지 궁금한 점들이 있어 리뷰 요청과 함께 한가지 질문을 드립니다.
# 공통 고민
## Car - name property 접근 제한자 Private로 전환 논의
> 객체에게 getter()를 사용하여 상태값을 가져오는 것 보다는 메시지를 던지도록 구조를 바꿔 데이터를 가지는 객체가 일하 도록 한다.
Car의 name 같은 경우는 RaceCarGameController 에서 단순 formatting을 할 때 만 사용합니다.
따라서, 저희는 private으로 제한하지 않았습니다.
이에 대해 리뷰어님의 의견을 듣고 싶습니다!!
- RaceCarGameController
<img src ="https://github.com/woowacourse/kotlin-racingcar/assets/87055456/2d0d50de-5861-4b71-9c24-179ce5645632"/>
## 개인적인 고민

2024-02-15 13:31 UTC, malibinYun requested changes
1단계 미션 고생 많으셨어요!
마지막에 남겨주신 질문은 따로 코멘트로 생각을 남겨둘게요 :)
피드백 반영 후 다시 리뷰 요청 해주세요! 🙂

2024-02-15 13:31 UTC, malibinYun commented on docs/README.md
> +
요구사항을 상세하게 정리해주셨네요 👍

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/NumberGenerator.kt
> +}
랜덤 요소를 분리해주셨네요 👍
fun interface 도 써주시다니, 코틀린 문법에 관심이 많으신가보네요 :)

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +    val name: String,
> 객체에게 getter()를 사용하여 상태값을 가져오는 것 보다는 메시지를 던지도록 구조를 바꿔 데이터를 가지는 객체가 일하 도록 한다.
Car의 name 같은 경우는 RaceCarGameController 에서 단순 formatting을 할 때 만 사용합니다.
따라서, 저희는 private으로 제한하지 않았습니다.
이에 대해 리뷰어님의 의견을 듣고 싶습니다!!

그렇군요! 제한하지 않으셨군요!!!

어떤 의견이 궁금하신걸까요?_?
제한해볼 수도, 제한하지 않을 수도 있겠지요! 어떤 부분에 대한 의견이 궁금하신지 잘 모르겠네요 😅

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +    }
moveOrStop의 반환 값은 테스트 코드에서만 활용하고 있네요!

프로덕션 코드에서 사용하지 않는, 테스트 코드만을 위해 만들어진 기능으로 테스트를 작성한다면, 
그것은 정말로 코드 동작을 검증했다고 볼 수 있을까요?

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +    override fun compareTo(other: RaceCar) = (distance - other.distance)
Comparable을 활용해볼 수도 있겠지만, compareTo operator를 활용해보셔도 좋겠어요 🙂

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCarGameController.kt
> +    private var trialCount: Int = 0
멤버변수를 활용하지 않고 클래스를 구성해보는 방법도 고민해보는 건 어떨까요?

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCars.kt
> +    }
equals & hashcode를 구현하신 이유가 궁금해요! 🙂

2024-02-15 13:31 UTC, malibinYun commented on src/main/kotlin/RaceCars.kt
> +    }
특별히 팩터리 메서드를 추가로 선택한 이유가 궁금해요! :)

이유에 상관없이, 부생성자를 활용하는 방법도 연습해보시면 좋겠네요 🙂

2024-02-15 13:31 UTC, malibinYun commented on src/test/kotlin/RaceCarTest.kt
> +    }
`@ParameterizedTest`를 활용해보는 건 어떨까요?

2024-02-15 13:31 UTC, malibinYun commented on src/test/kotlin/RaceCarsTest.kt
> +        val car = RaceCar("june").apply { moveOrStop(4) }
moveOrStop을 호출하지 않고, 생성자에서 초기 거리 값을 넘길 수 있게 객체를 구성한다면 손쉽게 초기 상태를 세팅해볼 수 있겠어요 :)
이 부분은 어려울 수 있으니 반영하지 않으셔도 좋아요 :)
나중에라도 꼭 고민해보시면 좋겠어요!

2024-02-15 13:40 UTC, malibinYun commented
> 페어와 코드를 작성 중에 커밋 타이밍을 놓치는 경우가 많았습니다.
서로 말이 잘 통하다 보니 코드 짜는것에 집중하느라 커밋을 깜빡하고 안하는 경우도 많았구요.
그러다 보니 커밋 로그를 보았을 때 어떤 코드를 수정했는지 알아보기 힘들고, 뭉텅이로 커밋 남긴 기능이 굉장히 많습니다.
의식적으로 커밋을 챙기는 것이 쉽지 않은데, 어떻게 하는 게 좋을까요?

기능 요구사항을 적었지만, 체크리스트로써 활용하지는 않으셨군요!
기능 요구사항대로 기능 단위를 나누고, 해당 기능 단위 만큼 커밋 단위를 쪼개면 돼요 :)
물론 굉장히 오랜 연습이 필요한 작업이에요. 처음에는 기능 단위 조차 쪼개는 게 어려울 거예요. 가늠 조차 잘 되지 않거든요.

커밋을 깜빡하고 하지 않았다면, 지금껏 작성했던 코드에서 어떻게하면 기능대로 나눠볼 수 있을지 역으로 고민해보셔도 좋겠어요 🙂


> 기능을 한 가지 작성하다 보면 구조를 수정해야 하는 경우나, 다른 기능을 수정하게 될 경우 등이 개인적으로도 빈번한데요.
이런 경우는 기능 단위로 커밋을 남기기가 쉽지가 않은데, 처음부터 기능 별 분리를 깔끔하게 하는 것이 답일까요?

제 친구가 늘 하는 말이 있는데요,

### 키보드에서 손 떼!!!!!! 어딜 코드부터 치려해?!

이에요 :)

건물을 지을 때 가장 시간이 오래걸리는 작업은 설계도를 작성하는 것이라고 해요.
실제 건물을 지을 때는 설계대로 대로 짓게되지요. 중간에 설계가 바뀌어서 다 다시 부수고 다시 지어 올리는 일은 거의 없지요.
그런 것 처럼 코딩도 똑같아요.
코드는 그저 생각을 옮겨 적을 도구일 뿐, 설계를 제대로 해두어서, 코드 치는 일은 그저 노가다 작업일 뿐으로 만들어야해요.

그만큼 다양한 상황에서 어떤 변경점이 생겨나고, 어떤 영향이 미칠 수 있는지 종합적으로 머릿속으로 그려낼 수 있어야겠지요!
그림으로라도 표현해서 어떤식으로 변경될지 가늠해볼 수 있겠어요.
기능 요구사항 목록을 그렇게 활용해보는 건 어떨까요? 🙂

2024-02-16 01:35 UTC, aprilgom commented on src/main/kotlin/RaceCar.kt
> +    val name: String,
Car의 name 값을 어딘가에 사용할 일이 있었는데, 코드를 계속 수정하다 보니 고민했던 부분의 코드가 거의 남아있질 않네요.. commit을 좀 더 잘 나눠서 열심히 남겼다면 어느 부분에서 이런 고민을 했는지 보기 쉬웠을 텐데 아쉬워요. 구조 수정을 계속 했는데, 커밋 로그로 남아있질 않아요 ㅠㅠ.. 개인적인 고민에 commit에 대한 부분을 적은 것도 이 때문이었어요.

페어와 고민했던 점에 대해 기억을 되짚어보자면요..

Car의 name을 읽기 전용으로 설정해 Car가 변조되는 것은 허용하지 않으나, Car의 name 값을 제한없이 Car 외부에서 알아버린다면 우리가 의도하지 않은 방식으로 사용될 수도 있는데 이것을 막아야 맞지 않는가에 대한 고민이였어요. 그런 의도치 않은 사용은 버그의 원인이 될 수 있으니까요. 거기에 더해 Car의 멤버 변수를 아예 노출시키지 않고자 하는 의도도 있었어요.

하지만 문제가 있었어요. name값을 Car 외부에서 누군가는 알아야 했거든요. 우승자의 이름을 출력해야 하는데 private로 잠궈버리면.. 이름을 안 알려주는데 우승자 발표에서 이름을 불러야 하는 상황이 된거죠. 제한은 해주고 싶은데, 값은 어떻게든 밖에서 알아야 하고.

하지만 당장에 주어진 요구사항에서 name이 쓰이는 곳을 봤을 때, 이런 부분들까지 걱정할 필요는 없다 생각해 private로 제한을 해주지 않고 넘어갔는데요, 보통 이런 부분까지 private로 막고 노출을 시키지 않는 편이 좋을까요? 아니면 그냥 선택의 문제, 케이스 바이 케이스로 여기고 넘어가는 게 좋을까요?

2024-02-16 05:12 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +    val name: String,
>  Car의 name 값을 제한없이 Car 외부에서 알아버린다면 우리가 의도하지 않은 방식으로 사용될 수도 있는데 이것을 막아야 맞지 않는가에 대한 고민이였어요.

name 멤버변수는 private이지만, getter가 따로 뚫려있는 경우에는 말씀해주신 고민점을 해결해주는 방법이었나요 ?_?

또, Car.name을 의도하지 않은 방식으로 사용하는 경우는 어떤 예시가 떠올라서 고민이되었던 걸까요 ?_?
출력용으로 써야하는데, name.length를 보고, 그것을 랜덤 시드로 취급한 다음에, 랜덤 컬러를 뽑아낸 다음.. 자동차의 색깔로써 써버리는 방법... 뭐 이런걸까요?

---

이런 경우는 어떠신가요?
대학교 학식 메뉴를 보여주는 앱을 만드는데, 학교 사이트 마다 형식이 모두 달라서 웹 크롤러를 학교 웹사이트마다 만들어서 구현한 앱이 있다고 상상해볼게요.
A 대학교에서 웹페이지를 리뉴얼한다면, 기존에 잘 동작하던 크롤러가 더 이상 원하는 정보를 제대로 가져오지 못하게 되겠지요!
심지어 학식 메뉴판의 주소또한 바뀌었다면? 아예 404 에러를 반환해버리겠지요.

이 일화가 명확하게 정답이 있지는 않아요.
당연히 학교는 알바 아니고, 크롤러 만든 사람이 잘못한 거 아니야? 라고 생각해볼수도 있겠어요.
일반적으로는 그럴지도 모르겠어요.

만약, 학교보다 그 앱이 훨씬 유명하고, 모든학생이 사용한다면, 학교가 리뉴얼한 페이지 때문에 전교생이 그 학교에 불만이 생길수도 있겠지요. 그렇다면 주객 전도 되어서, 페이지를 리뉴얼하는 사람은 크롤러가 호환될 수 있도록 고려를 해야할수도 있겠지요.

---

답이 없어서 답답하실 것 같아요.
하지만 그만큼 개발의 세계에는 정답이 존재하지 않아요. 제한된 상황과 제한된 자원 안에서 결과를 만들어내야하기 때문이에요.
그렇기 때문에 옮고 그럼을 떠나서, 본인이 해당 결정을 내린 이유가 가장 중요해요.

결정한 이유에는 어떤 장단점이 있었고, 무엇을 포기해서 무엇을 취했으며, 어떤 결과를 얻으셨나요?
다른 길을 선택했다면, 위 내용이 어떻게 바뀌었나요?

2024-02-16 08:26 UTC, aprilgom commented on src/main/kotlin/RaceCars.kt
> +    }
RaceCars에서 팩토리 메서드를 쓰기 전에는 부 생성자를 이용해보려 했었습니다. 부 생성자를 만들 때 RaceCars(List<String> names, NumberGenerator numGen)로 기존 생성자와 비슷하고 일관된 방식으로 만들고 싶었는데요, 알아보니 제네릭은 컴파일 타임에서는 타입 검사를 하지만, 런타임에서는 제네릭의 타입 검사를 할 수 없었습니다. (List<Car>든 List<String>이든 동일한 List 시그니쳐로 취급) 그러니 foo(List<String>)와 foo(List<Car>)는 런타임에서는 foo(List), foo(List)로.. 구분할 수 없게 되는거죠.

 JVM에서 돌아갈 때 두 생성자가 동일한 시그니쳐를 가질거란 생각을 페어인 오둥이가 말하기 전까지 생각 못했습니다. 이 문제를 해결하기 위해 부생성자에 @JvmName 어노테이션을 붙여서 시그니쳐를 바꿔주려 했으나, constructor에는 @JvmName 어노테이션 사용이 불가능했어요.

그래서 그냥 팩토리 메서드로 구현하기로 했었습니다.

2024-02-16 08:31 UTC, aprilgom commented on src/main/kotlin/RaceCars.kt
> +    }
RaceCars 의 from 팩토리 메서드를 테스트할 때 equals가 필요하게 되서 구현했습니다.

RaceCars(”a,b,c”, numberGenerator) 와 RaceCars(listOf(Car(”a”), Car(”b”),Car(”c”), numberGenerator)를 비교하여 두 객체가 같은 값들을 가지고 있다면 테스트를 통과하는 방식으로 만들어 봤는데요, moveOrStop 메서드에서 말씀주신 것처럼 단지 테스트를 위한 코드가 아닌가 생각이 들어요. 프로덕션 코드에서는 RaceCars는 단 하나만 필요하고, 비교할 일이 없으니까요. 다만 equals와 hashcode를 지웠을 경우에는 생성자가 제대로 작동하는지 테스트를 어떻게 하는 것이 좋을까요? 힌트를 좀 부탁드려도 될까요? 🥺

2024-02-16 08:33 UTC, aprilgom commented on src/main/kotlin/RaceCar.kt
> +    override fun compareTo(other: RaceCar) = (distance - other.distance)
operator fun compareTo(other: RaceCar) 를 말씀하시는게 맞을까요?

https://github.com/aprilgom/kotlin-racingcar/blob/59b9870b8dbd7c42b7ce14115fccfb69d2f26c77/src/main/kotlin/RaceCars.kt#L11-L12

여기서 처럼 컬렉션 함수를 사용하려면, Comparable을 활용하는게 맞지 않을까 싶어 일단 이대로 두었습니다!

2024-02-16 08:39 UTC, aprilgom commented on src/test/kotlin/RaceCarsTest.kt
> +        val car = RaceCar("june").apply { moveOrStop(4) }
RaceCar에 부 생성자를 새로 만들어서 distance를 초기화 시켰는데요, 이러면 클래스 내부에 distance 변수가 있다는 것을 외부로 노출시킨다는 생각이 들어요. 더 좋은 방법이 없을까요..

2024-02-16 10:04 UTC, aprilgom commented on src/test/kotlin/RaceCarsTest.kt
> +        val car = RaceCar("june").apply { moveOrStop(4) }
RaceCar에 부 생성자를 새로 만들어서 distance를 초기화 시켰는데요, 이러면 클래스 내부에 distance 변수가 있다는 것을 외부로 노출시킨다는 생각이 들어요. 더 좋은 방법이 없을까요..

2024-02-16 10:06 UTC, aprilgom commented on src/main/kotlin/RaceCarGameController.kt
> +    private var trialCount: Int = 0
cars와 trialCount를 private val로 전환했습니다!

2024-02-16 10:08 UTC, aprilgom commented on src/main/kotlin/RaceCar.kt
> +    }
test는 toString 값을 검사하도록 하여 distance가 실제로 바뀌는지 검사하도록 했습니다.

2024-02-17 05:40 UTC, aprilgom commented on src/main/kotlin/RaceCar.kt
> +    val name: String,
> name 멤버변수는 private이지만, getter가 따로 뚫려있는 경우에는 말씀해주신 고민점을 해결해주는 방법이었나요 ?_?

음.. private name 에 getter만 따로 뚫어놓는건 결국 val name과 다를 바 없을 것 같아요. 아마 Car의 name을 Cars에서만 접근 가능하게 하면 이런 고민을 해결할 수 있을 것 같은데.. 
> 또, Car.name을 의도하지 않은 방식으로 사용하는 경우는 어떤 예시가 떠올라서 고민이되었던 걸까요 ?_?
출력용으로 써야하는데, name.length를 보고, 그것을 랜덤 시드로 취급한 다음에, 랜덤 컬러를 뽑아낸 다음.. 자동차의 색깔로써 써버리는 방법... 뭐 이런걸까요?

네 맞아요! 그런데, 사실 이 프로젝트에서 name을 어디 가져다 엉뚱한 곳에 쓸 가능성은 별로 없어보여요.. 그래서 페어와 논의할때 저는 val로 하자는 쪽이었습니다 ㅎㅎ.. 아래 말씀하신 걸 보고 조금 알 것 같습니다!

>이런 경우는 어떠신가요?
대학교 학식 메뉴를 보여주는 앱을 만드는데, 학교 사이트 마다 형식이 모두 달라서 웹 크롤러를 학교 웹사이트마다 만들어서 구현한 앱이 있다고 상상해볼게요.
A 대학교에서 웹페이지를 리뉴얼한다면, 기존에 잘 동작하던 크롤러가 더 이상 원하는 정보를 제대로 가져오지 못하게 되겠지요!
심지어 학식 메뉴판의 주소또한 바뀌었다면? 아예 404 에러를 반환해버리겠지요.
이 일화가 명확하게 정답이 있지는 않아요.
당연히 학교는 알바 아니고, 크롤러 만든 사람이 잘못한 거 아니야? 라고 생각해볼수도 있겠어요.
일반적으로는 그럴지도 모르겠어요.
만약, 학교보다 그 앱이 훨씬 유명하고, 모든학생이 사용한다면, 학교가 리뉴얼한 페이지 때문에 전교생이 그 학교에 불만이 생길수도 있겠지요. 그렇다면 주객 전도 되어서, 페이지를 리뉴얼하는 사람은 크롤러가 호환될 수 있도록 고려를 해야할수도 있겠지요.

오작동에 대해서 name값을 가져가 사용하는 쪽의 책임으로 할지, 아니면 애초에 사용법을 제한해버릴지는 명확하게 정답이 없다! 
상황을 보고 판단해야 할 것이나..

>하지만 그만큼 개발의 세계에는 정답이 존재하지 않아요. 제한된 상황과 제한된 자원 안에서 결과를 만들어내야하기 때문이에요.
그렇기 때문에 옮고 그럼을 떠나서, 본인이 해당 결정을 내린 이유가 가장 중요해요.

자신의 결정에는 설득력 있는 근거가 필요하다! 라고 이해했는데 맞을까요?

2024-02-18 02:35 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요 :)
다음 미션을 위해 머지하겠습니다.
다음 미션에서는 Controller도 테스트 가능하도록 구성해보세요! 🙂

2024-02-18 02:35 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +    val name: String,
네! 이해하신 내용이 맞아요 :)
스스로가 짠 코드에 대해 왜 이렇게 짰냐고 물어보면, 바로 그에 대한 썰을 풀 수 있을 정도로,
코드 한 줄 한 줄에 결정에 대한 이유를 담아보는 연습을 해보세요 🙂

2024-02-18 02:35 UTC, malibinYun commented on src/main/kotlin/RaceCar.kt
> +        }
어떤 이름이었는지 에러 메시지에 담아 표시해보는 건 어떨까요?
어떤 차이점이 생길까요?

2024-02-18 02:35 UTC, malibinYun commented on src/main/kotlin/RaceCars.kt
> +        return winnerCars
`it.compareTo(winnerCar) == 0` 이 코드를 짜지 않은 사람이 이 수식을 보았을때, 어떤 의도가 담겨있는지 한 번에 알 수 있을까요?

2024-02-18 02:35 UTC, malibinYun commented on src/main/kotlin/RaceCarGameController.kt
> +    }
lazy 때문에 이런 코드가 나오게 된 것 같네요 :)
"멤버 변수"를 활용하지 않고 클래스를 구성해보는 방법을 연습해보세요 :)

2024-02-18 02:36 UTC, malibinYun commented on src/main/kotlin/RaceCars.kt
> +    }
`class` 와 `data class` 의 차이인, `data` 키워드는 어떤 역할을 할까요?

2024-02-18 02:40 UTC, malibinYun commented on src/main/kotlin/RaceCars.kt
> +    }
맞아요 :) 
제네릭을 활용하는 곳에는 컴파일 타임에 타입 소거 (type erasure) 가 일어나게 돼죠.
https://kotlinlang.org/docs/generics.html#type-erasure

타입 소거때문에 팩터리 메서드를 활용한 선택은 합리적이라 생각해요!
타입 소거로 어떤 문제점들이 생겨날 수 있는지 문법 공부를 해보셔도 좋겠어요 :)

2024-02-18 02:40 UTC, merged

2024-02-18 04:01 UTC, aprilgom commented on src/main/kotlin/RaceCars.kt
> +    }
toString이나 equals, hashCode, ComponentN, copy를 컴파일러가 대신 작성해줘서 보일러 플레이트를 줄이는 키워드로 알고 있습니다. 자동 작성되는 코드를 전혀 쓰지 않으니 equals, hashCode를 지우기 이전에도 data 키워드는 굳이 필요가 없어 보이네요. 
step2 진행하기 전에 지우고 가겠습니다!