[자동차 경주 구현] 채채 미션 제출합니다.
woowacourse/kotlin-racingcar pull request #99
Opened 2024-02-15 07:13 UTC by chaehyuns

## step 1 미션 제출

안녕하세요 리뷰어님, 페어 1조 채채입니다 :)
우테코 첫 미션이어서 그런지 저희 페어가 잘 구현했는지, 어떤게 좋은 코드인지에 대한 고민을 많이 하게 되었습니다.
부족한 실력이지만 잘부탁드리겠습니다!

---

### 질문 🤔 
- InputConverter나 InputVaildator 등은 객체 자체에서 어떠한 상태를 저장하지 않고, 함수의 인자로만 값을 받아옵니다. 이 경우 object를 사용하면 좋을지, 일반적인 class를 사용하면 좋을지 궁금합니다.
- 현재 model에 대한 검증을 input 패키지 내에서 수행하고 있는데, 이 방법이 적절한 걸까요? 현재 InputView의 역할이 너무 크지는 않은지 궁금합니다.
- private을 지키기위해 getter와 setter를 자동 생성해주는 kotlin의 장점을 살리지 못하고 코드 복잡도가 상승하였는데, private를 지키는게 더 중요한 기준이 따로 있는지 궁금합니다.

2024-02-15 13:05 UTC, malibinYun requested changes
1딘계 미션 고생 많으셨어요 :)
좋은 코드에 대해 고민을 많이하셨군요!!
페어 두 분이서 결론 내린 좋은 코드란 무엇이었나요?! 너무 궁금해요! 😀

생각해보면 좋을 점들에 코멘트 남겨두었어요.
피드백 반영 후 다시 리뷰 요청 부탁드려요 :)

2024-02-15 13:05 UTC, malibinYun commented on README.md
> +---
기능 요구사항을 상세하게 정리해주셨네요! 👍👍

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/constants/GameConstants.kt
> +}
상수 만을 가지는 파일을 여러 파일에서 나눠, 상수를 관리하게 된 이유가 궁금해요! 🙂

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +        }
현실세계를 차용해서 객체를 만들어보는 건 어떨까요?

시도 횟수가 어려번의 action을 하게하는 것.. 이것은 현실세계에서 찾기에는 어려워보여요.

경주를 위해 자동차들이 달릴 경주장을 객체로 표현해보는 건 어떨까요?

최대한 객체에게 메시지를 던져 보세요!

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/model/Car.kt
> +    private var forwardCount = 0
> private을 지키기위해 getter와 setter를 자동 생성해주는 kotlin의 장점을 살리지 못하고 코드 복잡도가 상승하였는데, private를 지키는게 더 중요한 기준이 따로 있는지 궁금합니다.

미션을 진행하면서 두 크루는, 어떤 기준으로 private를 지키는 게 더 중요하셨나요?_?

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/service/ForwardService.kt
> +    }
다른 객체가 자동차를 받아서 검증 후 직접 움직이게도 할 수 있지만,
자동차에게 숫자를 주어서 자율적으로 움직일지 말지 역할을 부여해보는 건 어떨까요?

자동차에게 메시지를 던져보세요 :)

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/view/input/InputConverter.kt
> +}
> InputConverter나 InputVaildator 등은 객체 자체에서 어떠한 상태를 저장하지 않고, 함수의 인자로만 값을 받아옵니다. 이 경우 object를 사용하면 좋을지, 일반적인 class를 사용하면 좋을지 궁금합니다.

어떤 것이 나을까요?!
각각이 어떤 특징점들을 갖고 있는지 잘 비교해보고 적절해 보이는 방법을 스스로 선택해보면 좋겠어요!
class와 object는 어떤 차이점이 있나요?_?

2024-02-15 13:05 UTC, malibinYun commented on src/main/kotlin/racingcar/view/input/InputValidator.kt
> +class InputValidator {
> 현재 model에 대한 검증을 input 패키지 내에서 수행하고 있는데, 이 방법이 적절한 걸까요? 현재 InputView의 역할이 너무 크지는 않은지 궁금합니다.

옳고 그름을 떠나서, InputValidator객체로 검증에 대한 역할을 한꺼번에 묶은 이유가 궁금해요! 🙂

스스로 적절치 않았다고 생각했다면, 어떤 이유였을까요? 
어떤 다른 방법으로 스스로가 생각한 단점을 보완해볼 수 있을까요?

2024-02-15 13:05 UTC, malibinYun commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        assertThat(car1.compareTo(car2)).isEqualTo(0)
car1.compareTo(car2) 이 0 임은 어떤 의미인지 코드를 짜지 않은 사람이 한 번에 이해할 수 있을까요?

car1를 움직였으니, car1의 거리가 원하는 만큼 변경되었는지 검증해보는 건 어떨까요?
car2가 정말로 필요한 비교군이었는지 고민해보세요 :)

2024-02-16 08:09 UTC, chaehyuns commented on src/main/kotlin/racingcar/constants/GameConstants.kt
> +}
저희도 상수 파일을 만들어서 관리할까 혹은 class안에 내부적인 companion object를 둬서 관리를 할까 고민을 하다가 MIN_CAR_NAME_LENGTH , MAX_CAR_NAME_LENGTH 등등 게임의 룰에 대한 정보를 한곳에 모아 놓는 방식이 더 확장성이 좋다고 생각해서 Game에 관련된 상수, 출력에 관련된 상수, 에러에 관련된 상수로 나눠서 관리하자는 결론을 내렸던거 같습니다!

2024-02-16 08:27 UTC, chaehyuns commented on src/main/kotlin/racingcar/model/Car.kt
> +    private var forwardCount = 0
Car의 forwardCount가 우승자를 결정하기 때문에, 
외부에서 forwardCount에 접근이 되어 예기치 못한 오류가 발생하는 것을 막고자 했습니다. 
하지만 가시성 변경자(private set)를 통해 setter 함수에 대한 접근을 제한하는 방식으로 다시 수정하는게 더 옳다는 생각이 들어 코드 수정을 해보고자 합니다!

2024-02-16 08:31 UTC, chaehyuns commented on src/main/kotlin/racingcar/service/ForwardService.kt
> +    }
이번에도 객체에 대한 이해를 높혀 객체에 메시지를 던지는 방식으로 수정해서 다시 돌아오겠습니다!!

2024-02-16 08:56 UTC, chaehyuns commented on src/main/kotlin/racingcar/view/input/InputValidator.kt
> +class InputValidator {
validator가 늘어나면서 validateEmpty 함수 등 여러 중복되는 부분이 생긴다고 생각하여 InputValidator 하나의 객체로 생성을 했습니다!
domain에서 검증을 해야하는지 아니면 input에서 검증을 해야하는지 크루마다 생각이 달라 리뷰어님의 의견이 궁금했습니다🤔

2024-02-16 09:02 UTC, chaehyuns commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        assertThat(car1.compareTo(car2)).isEqualTo(0)
`car1.compareTo(car2) 이 0 임은 어떤 의미인지 코드를 짜지 않은 사람이 한 번에 이해할 수 있을까요?` 라는 부분에서 어떤 문제점이 있었는지 확인하게 되었습니다.
다시 한번 고민해서 코드를 수정하겠습니다! 😁

2024-02-16 09:15 UTC, chaehyuns commented on src/main/kotlin/racingcar/view/input/InputConverter.kt
> +}
상태를 저장하지 않고 단순한 함수 호출로 로직을 수행하는 경우 object를 사용하는 등 특징점을 사용해서 선택하겠습니다! 감사합니다!

2024-02-16 09:29 UTC, chaehyuns commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +        }
아! 저도 스스로 객체에 대한 이해가 아직 부족하다고 느꼈습니다! 🥹
시도 횟수가 어려번의 action을 하게하는 것은 현실세계에서 찾기 어려운 부분이 맞는거 같습니다!
Race 객체를 만들어서 Car에 대한 이동을 제어하려고 하는데, 이해가 바르게 된건지 궁금합니다 🤔

2024-02-17 09:28 UTC, chaehyuns commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        assertThat(car1.compareTo(car2)).isEqualTo(0)
고민한 결과 car2를 두는 것보다 현재의 포지션을 저장하고 현재의 포지션에 1을 더한 값과 동일한지 test하는 형식으로 수정했습니다!

2024-02-17 09:42 UTC, chaehyuns commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +        }
코드를 수정하면서 경주는 비지니스 로직적인 측면이 강해서 RaceService 를 사용해서 제어하는 방식으로 코드를 수정했습니다.
리뷰어님이 말씀해주신 경주를 위해 자동차들이 달릴 경주장을 객체로 표현한다는게 어떤 걸 뜻하는지 살짝 더 자세하게 알려주실 수 있을까요? 🥲

2024-02-18 02:52 UTC, malibinYun commented on src/main/kotlin/racingcar/constants/GameConstants.kt
> +}
이후 게임 내의 에러를 표시하는 경우, ErrorConstants GameConstants 둘 중 어느 파일에 위치시켜야할지 구분이 애매해질지도 모르겠어요.

저는 해당 상수를 활용하는 객체 스스로가 가지고 있는 것이 가장 응집도 높은 방법이라 생각해요. 카테고리로 묶더라도 결국 상수 모음 파일은 시간이 지날수록 매우 많아지기 때문이에요.

두 방법 모두 장단점이 있는 방법이라 생각해요. 저는 이렇게 생각하고, 스스로가 생각한 방법에 대해서 지금처럼 본인이 결정하게 된 이유를 잘 가져가보길 바라요 🙂

2024-02-18 02:55 UTC, malibinYun commented on src/main/kotlin/racingcar/controller/RacingCarController.kt
> +        }
경주장에는 자동차들이 있어야겠지요.
자동차들을 가지는 경주장 객체를 만들고, 그 경주장 객체에게 경기를 시작하라는 메시지를 던짐으로써 경주장은 가지고있는 자동차들에게 경주를 하라고 만들겠지요!

위 일련의 과정들을 객체로 표현해보세요 :)
RaceService에서 이름과 몇가지 부분만 조금 고치면 바로 경주장 객체를 만들 수 있겠어요

2024-02-18 03:03 UTC, malibinYun commented on src/main/kotlin/racingcar/view/input/InputValidator.kt
> +class InputValidator {
inputView를 사용하지 않게 된다면 어떻게 될까요?
이 로직을 모두 안드로이드 프로젝트에 옮기면, 콘솔에 대한 코드는 모두 사용하지 않게 되겠지요.
이때 `Car("아무튼비정상적인이름")` 를 생성자를 통해 생성한다면, 이 Car 객체는 프로그램에서 돌아다녀도 괜찮은 유효한 객체일까요?

---
제 의견은, 검증은 어디서든 안해서 좋을 곳이 없다 예요.
역할에 맞는 검증까지만 수행하는 것을 선호해요. 입력 값에 대한 검증이라면 입력 값에 대한 검증만. 도메인의 검증이라면 도메인에는 해당의 검증만.
역할에 따라 적절히 분리하는 것을 선호해요 🙂

2024-02-18 03:15 UTC, malibinYun approved these changes
1단계 미션 고생 많으셨어요.
생각해보면 좋을 점들에 코멘트 남겨두었어요!
피드백은 다음 미션에 반영해주세요 :)
다음 미션을 위해 머지할게요! 2단계 미션도 화이팅이에요 💪

2024-02-18 03:15 UTC, malibinYun commented on src/main/kotlin/racingcar/model/Car.kt
> +        private set
getter는 공개하고, setter는 감추고.
kotlin property 문법을 잘 활용해주셨네요! 👍

2024-02-18 03:15 UTC, malibinYun commented on src/main/kotlin/racingcar/service/WinnerService.kt
> +    }
`it.compareTo(maxCarPosition) == 0` 이 코드를 짜지 않은 사람이 이 수식을 보았을때, 어떤 의도가 담겨있는지 한 번에 알 수 있을까요?

2024-02-18 03:15 UTC, malibinYun commented on src/test/kotlin/racingcar/ExceptionTest.kt
> +    @ValueSource(strings = ["", " ", ",,,"])
`@NullAndEmptySource` 를 참고해보세요 :)

2024-02-18 03:15 UTC, malibinYun commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        every { randomGenerator.generate() } returns GameConstants.FORWARD_FLAG_NUMBER
이 미션은 mock 라이브러리의 도움 없이도 랜덤에 대한 테스트를 할 수 있게 프로젝트를 구성할 수 있어요 :)
레벨 1 의 모든 미션에서 구성 가능하니, mock 라이브러리의 사용은 하지 말아주세요.

외부에서 제어 불가능한 값을 넘겨주도록 구현해보세요 :)
Car 객체에게 적용했던 것 처럼요!

2024-02-18 03:15 UTC, malibinYun commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        )
forward() 메서드는 Car 내부에서 사용하고 있지만, 사실상 테스트를 위한 코드라고 봐도 무방해보여요.
tryForward() 메서드를 활용하지 않은 이유가 궁금하네요!

---

더 나아가서, 생성자를 통해 초기 거리 값을 넘길 수 있게 객체를 구성한다면 손쉽게 초기 상태를 세팅해볼 수 있겠어요 :)
이 부분은 어려울 수 있으니 반영하지 않으셔도 좋아요 :)
나중에라도 꼭 고민해보시면 좋겠어요!

2024-02-18 03:15 UTC, malibinYun commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        assertThat(winners[0].toString()).isEqualTo("chae")
Car의 name을 공개하지 않고 toString으로 접근하게 된 이유가 궁금해요 :)

2024-02-18 03:15 UTC, merged

2024-02-19 04:34 UTC, chaehyuns commented on src/main/kotlin/racingcar/model/Car.kt
> +        private set
감사합니다 :)

2024-02-19 04:37 UTC, chaehyuns commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        )
고민해볼 사항이 하나 더 생겼네요! 좋은 말씀 감사합니다! 😁

2024-02-19 05:00 UTC, chaehyuns commented on src/main/kotlin/racingcar/service/WinnerService.kt
> +    }
변수명에 대한 고민과 compareTo를 꼭 사용해야하는지에 대한 고민을 하고 다시 코드를 수정해보겠습니다!!

2024-02-19 05:01 UTC, chaehyuns commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        every { randomGenerator.generate() } returns GameConstants.FORWARD_FLAG_NUMBER
네 이 부분도 참고하여 코드를 수정하겠습니다!!!

2024-02-19 06:04 UTC, chaehyuns commented on src/test/kotlin/racingcar/ServiceTest.kt
> +        assertThat(winners[0].toString()).isEqualTo("chae")
다시한번 생각해보니 val 로 선언하여 굳이 private로 선언할 필요가 없음을 알게 되었습니다! 꼼꼼한 리뷰 감사합니다!